### ISSUE TITLE
Issues for Inline Comments PR

### ISSUE THREAD

**Issue by ungb** [github/VisualStudio#1020]
This is a issue to keep track of all suggestions and bugs found for pr:

https://github.com/github/VisualStudio/pull/1004

**Comment by ungb** [comment]
Inline Comments known issues
- [ ] Fork doesn’t work yet for PR, can’t
- [ ] Performance is not great right now
- [ ] 1 issue, pr

We should:
- [ ] Test enterprise as well to make sure everything still works.

**Comment by grokys** [comment]
I'm going to drop the notes I took from the meeting here because I'm not sure how you want to organize:

- Display conversation reply control in a non-scrolling area at the bottom of the peek window if the comment thread extends past the bottom of the view
- Change glyph color for open comment thread
- Show the "Add Comment" icon when hovering over the line rather than just when hovering over the margin
- In the changed files tree, display the total number of comments for the subtree next to folders
- Add a "View on GitHub" button in the comment thread
- Display the number of comments in a thread in the glyph?
- Mark read/unread comments?

And here are a couple of things that we're already intending to do:

- In the peek comment thread, display a tooltip for the next/previous comment button including the associated key binding for discoverability (yes there are key bindings for next/previous comment but no-one is likely to find them otherwise!)
- Show a tooltip with the first N comments when hovering over a comment glyph

I will add to this list as I remember more!

**Comment by tierninho** [comment]
@grokys I believe I found a bug which crashes VS. Not sure how to access the logs yet, but reproducing steps are here:

- Click (comment X) in PR, which should link user to existing comment + reply field in diff view
- Reply with `blank space`, submit

<img width="176" alt="screen shot 2017-06-28 at 11 50 15 am" src="https://user-images.githubusercontent.com/14828183/27647005-357b00da-5bf8-11e7-9e17-66866e5eb5d0.png">
<img width="372" alt="screen shot 2017-06-28 at 11 50 46 am" src="https://user-images.githubusercontent.com/14828183/27647006-357d75ea-5bf8-11e7-9984-e7c3189bd81c.png">

Tried it thrice and VS crashed and restarted each time.

**Comment by tierninho** [comment]
Adding all my recommendations here:
- [ ] Don't let user paginate if only one comment thread

**Comment by tierninho** [comment]
In diff view, on removed side, the user can open comment box on a line that has no changes, however no comments are not published. Upon clicking `comment`, the text is not saved.

<img width="371" alt="screen shot 2017-06-28 at 12 29 41 pm" src="https://user-images.githubusercontent.com/14828183/27648804-c2320d7a-5bfd-11e7-8f91-bc56d2d6119d.png">

**Comment by grokys** [comment]
@tierninho yes, you can change the theme from Tools -> Options -> Color theme.

And yes, it looks terrible at the moment with the dark theme ;)

**Comment by grokys** [comment]
> When opening comments in diff view (by clicking the X comments number), how do we determine which comment should be opened? After testing, it always opened the same comment and not the thread last commented on.

Yes, currently the first comment thread is opened. We could open the most recently commented thread, but I think this ties into having read/unread status for comments. Might be worth promoting this to its own issue so we can discuss it further?

**Comment by tierninho** [comment]
Issue: Adding an `@-mention` does not appear to be notifying users if implemented from inline comments. The `@-mention` shows up correctly on dotcom, but no email is sent.

**Comment by tierninho** [comment]
Issue: User cannot scroll if error message is surfaced in the inline comments

<img width="415" alt="screen shot 2017-06-29 at 10 34 37 am" src="https://user-images.githubusercontent.com/14828183/27693262-e6362fd0-5cb6-11e7-869f-3339b3301398.png">

**Comment by grokys** [comment]
Regarding colors: f2cdce62fa639275aa7463deeb714fd619ab6683 fixes switching themes while a diff view is open. The comment glyphs are still displayed in black, but there is a gray/green/red background which makes them still visible. Not sure if contrast should be improved some more by making the glyphs white though:

![image](https://user-images.githubusercontent.com/1775141/27697566-f5c26462-5cf4-11e7-9d5f-1cd66bf3630a.png)

**Comment by paladique** [comment]
> Issue: Adding an @-mention does not appear to be notifying users if implemented from inline comments. The @-mention shows up correctly on dotcom, but no email is sent.

Does it show up in notifications at least @tierninho? I tried this on my test account and got an email and it's in my notifications.

![capture](https://user-images.githubusercontent.com/1414307/27713324-2e0e06e2-5cf9-11e7-88bb-19894bfafb4f.PNG)

**Comment by tierninho** [comment]
@paladique All good now, I add to add myself as a collaborator in my test repo :man_facepalming:

**Comment by tierninho** [comment]
Anchor is not set to the proper position when paginating from the Added to Removed side of the diff. The anchor position makes the view of the inline comment form hard to see. It should anchor to the top of the form so the user can see the whole form and not just a partial.

Inline form is on line 1. This is what I see when paginating:
<img width="777" alt="screen shot 2017-06-30 at 10 42 38 am" src="https://user-images.githubusercontent.com/14828183/27740830-301c8a8e-5d81-11e7-9b2c-00fa14f8ca2c.png">

Reproduce:
- Create a comment on line 1 of the Removed side
- Create a comment on of the Added side, click paginate button

This may also be a result of my settings or screen size.

**Comment by tierninho** [comment]
While comments are pending as part of the review process, the user on VS cannot post a comment. We do say "Validation pending" but perhaps this could be a little clearer. I suggest tailoring the message or just putting a error message and not allowing the user to even reply.

<img width="317" alt="screen shot 2017-06-30 at 10 56 31 am" src="https://user-images.githubusercontent.com/14828183/27741468-31cd1c34-5d83-11e7-9b47-4bb2fba3e6ed.png">
above has to wait for this to be cleared via review process:
<img width="678" alt="screen shot 2017-06-30 at 10 56 46 am" src="https://user-images.githubusercontent.com/14828183/27741469-31d3b45e-5d83-11e7-84c3-480fa170d1e8.png">

**Comment by jcansdale** [comment]
Margin is only visible when `Open File` is used, if there is already a diff view opened using `Compare File`.

E.g., this works:
![image](https://user-images.githubusercontent.com/11719160/27760829-7d621850-5e48-11e7-9518-eb2776a4351c.png)

But only because `Diff- DiffUtilities.cs` is already open. If you open `DiffUtilities.cs` directly the margin isn't visible. Not sure what's causing this.

**Comment by shana** [comment]
- [ ] if `GitClient` methods throw, the exceptions are swallowed and never reported back to the UI. This is not a new thing, but now if `Fetch` throws, the PR details view never finishes loading and gets stuck on the spinner.
   - Test this by switching the remote to an ssh url and try to open the PR details view

More generally, some calls like https://github.com/github/VisualStudio/blob/21821b22e86c1fc52ddea14fa43a25c1dc351ff1/src/GitHub.App/Services/PullRequestService.cs#L111 into `GitClient` are not ensuring that the urls are https. VS doesn't support ssh urls for remotes. This has probably been failing for a while but hasn't been caught because the UI doesn't report anything. It is in the log files though, so we should make sure the log files don't have exceptions when we test, even if it looks like everything is ok.

**Comment by shana** [comment]
- [ ] If there are new remote commits, comment box says comments are disabled until I push (I have no local changes or commits). The remote commits don't change the file I'm currently on, so even if there are new remote commits, they shouldn't affect the ability to comment on diffs that haven't been affected

![image](https://user-images.githubusercontent.com/310137/27834642-04047e02-60d8-11e7-88d4-c0bb5bc630f9.png)

- [ ] Promote to document from the diff view closes the comment box and doesn't do anything
- [ ] Comment box is too big
![image](https://user-images.githubusercontent.com/310137/27838529-91febc78-60eb-11e7-97ef-4acd11e2986c.png)

**Comment by shana** [comment]
- [ ] If clicking on a comment bubble opens the comment box, clicking on it again should probably close it so the user doesn't have to move the mouse all the way across the screen for that action

**Comment by shana** [comment]
- [ ] The date in the comment title should be a link to the url of that comment, for sharing

**Comment by shana** [comment]
- [ ] When the diff view is closed, the PR details view scrolls up, hiding the file selection. It's annoying when going through files one by one from the PR file list, as you have to scroll down again to find the last selected file and go to the next one.

**Comment by shana** [comment]
- [ ] Scrolling while comment box is open isn't feeling quite right. If there aren't any comments to scroll in the comment box, we should probably let the event bubble out to the diff/editor view so you can scroll the document without having to move the mouse away from the comment box.

**Comment by shana** [comment]
- [ ] There's no scrolling in the comment itself (if it's too long for the text box)

**Comment by tierninho** [comment]
If user is in the non-diff view, the comment count next to the file is showing the total number of comments which includes the entire diff. 

<img width="1043" alt="screen shot 2017-07-07 at 10 00 12 am" src="https://user-images.githubusercontent.com/14828183/27961035-6876ff2a-62fb-11e7-9fc0-35466703fb96.png">

I believe it should show only the count for the current "view" opened, as the user can paginate through only the comments in the current "view". 

For example, if the PR view is open then count of two comments should show in the GH window. If the master view open, then one comment should show. Perhaps say we change to a ratio instead, like "1/3"?

**Comment by tierninho** [comment]
Adding a comment to a line in green gutter scroll section works, however the comment is not found if I were to click on that line again. The comment count in the GH window does not increment either.

<img width="644" alt="screen shot 2017-07-07 at 10 19 06 am" src="https://user-images.githubusercontent.com/14828183/27961999-8da1ec12-62fe-11e7-8d3a-42fc82d806ac.png">

I can see the comment in PR on dotcom though. Not sure if this is the correct functionality. I would expect the comment to be sticky in VS and the comment count to increment.

<img width="1130" alt="screen shot 2017-07-07 at 10 20 18 am" src="https://user-images.githubusercontent.com/14828183/27962027-9dc17bd0-62fe-11e7-95e8-6fd0f5d56f08.png">

**Comment by ungb** [comment]
I broke this issue into multiple other issues.  See https://github.com/github/VisualStudio/labels/inline%20-comments for all the list of issues.  Please don't add more issues here as they can get more lost.  As we go forward I'll try to think of a better process on creating issues for new features.  

Thanks everyone here for testing, offering your suggestions and finding bugs! ✨ 👍 🎉 

For now, if you do find a new issue, please create a new issue and label it with `inline-comments`
