### ISSUE TITLE
TypeScript "Compile on save" does not work in VS2015 Update3

### ISSUE THREAD

**Issue by AhmerAli** [github/VisualStudio#1038]
I am developing angular 2 application in visual studio 2015 update 5. I am facing issue when I save the typescript file visual studio not watching changes. Below I provide my screenshots what I have done.

![01](https://user-images.githubusercontent.com/20426870/27939846-d7dc4b88-62e0-11e7-9fa7-3e8c0209748a.PNG)

![04](https://user-images.githubusercontent.com/20426870/27939853-df6f6cd6-62e0-11e7-95e8-46b8c424f61d.PNG)

![02](https://user-images.githubusercontent.com/20426870/27939855-df977a3c-62e0-11e7-941e-9b939dd01854.PNG)

![03](https://user-images.githubusercontent.com/20426870/27939856-dfb9065c-62e0-11e7-9888-db11c9cde770.PNG)

**Comment by grokys** [comment]
Hi @AhmerAli 

This is the repository for the GitHub Extension for Visual Studio, which doesn't have anything to do with Typescript (I know it's confusing with the repository being called `VisualStudio` and all).

The best way to send feedback on Visual Studio is to use the "Send Feedback" icon in Visual Studio's title bar (next to Quick Launch).

I'm going to close this issue as I don't think it's relevant here, but if you feel otherwise please comment 
explaining why you think it's relevant and I can re-open.
