### ISSUE TITLE
Issues scrolling in the PR details 

### ISSUE THREAD

**Issue by ungb** [github/VisualStudio#1042]
When the PR details view is scrolled and all editors are closed, the PR details pane scrolls back to the top, losing ones position in the changed files list.

/cc @tierninho for more info

**Comment by grokys** [comment]
More info: this only happens when the PR branch is currently checked out.

**Comment by grokys** [comment]
Seems to be caused by `MarkdownViewer` raising a `RequestScrollIntoView` event which causes the `ScrollViewer` to scroll it into view. First appeared in  55fa85f7de9e43e7c10962b43bd00d44adddddeb.

**Comment by grokys** [comment]
Seems to have been caused by the removal of this `TextBlock`/`Hyperlink`:

https://github.com/github/VisualStudio/commit/55fa85f7de9e43e7c10962b43bd00d44adddddeb#diff-ca5871601505a60a2f156f2e568e46ceL167

What I *think* is happening is that when the last editor window is closed, VS sets the focus to the first focusable control in the GitHub pane. Before this change, the `Hyperlink` was the first focusable control, and when the PR isn't checked there is the "checkout" hyperlink. However after this change, when the PR is checked out the first focusable control is the `MarkdownViewer`. Even if the `MarkdownViewer` is set to non-focusbale then the `TreeView` is focused, scrolling it to the top.
