### ISSUE TITLE
Clicking `git clone` without signing-in crashes VS

### ISSUE THREAD

**Issue by tierninho** [github/VisualStudio#1075]
When clicking `git clone` without signing-in, VS will crash. Not sure why we are able to clone without signing in. 

Recreate:
- While logged out, in team explorer window, click `x`on github sign-in section
- Github sign-in version 2 should appear with Clone option

<img width="345" alt="screen shot 2017-07-14 at 11 23 09 am" src="https://user-images.githubusercontent.com/14828183/28218700-5168c3a4-6887-11e7-9d94-0a965212f364.png">
<img width="311" alt="screen shot 2017-07-14 at 11 25 38 am" src="https://user-images.githubusercontent.com/14828183/28218699-5165fda4-6887-11e7-85bf-638c5ffaafd6.png">

No logs found.

v2.3.0.0, VS 2017, Windows 10.

**Comment by grokys** [comment]
Wow, I didn't even _know_ you could click the `x` there! Definitely a bug!

**Comment by grokys** [comment]
Seems that we decide whether to show this UI by checking if the invitation section is invisible, I think assuming that if it isn't visible then the user is logged in:

https://github.com/github/VisualStudio/blob/d9116de5dea77fb372642cb7bf3e1bc5f399ef2d/src/GitHub.TeamFoundation.14/Connect/GitHubConnectSection.cs#L180-L187

@shana I assume you weren't aware of the `x` to manually close the invitation section either? :D

**Comment by shana** [comment]
I was actually, that's why the different Clone|Create|Sign in appears, because the invitation section might get dismissed - Microsoft made that UI before they had us on the provider list, so if you sign in to VSO it will also hide the invitation section (and our UI with it), which is why that detection code is there to show the alternate UI.

You can click the clone button just fine regardless of sign in status, it should popup the authentication dialog before it shows the clone dialog if you're not signed in. If it's crashing, then it's a regression.
