### ISSUE TITLE
Invitation Card: Octocat logo is black on dark gray on the Visual Studio dark theme

### ISSUE THREAD

**Issue by artl93** [github/VisualStudio#110]
After installing the GitHub extension on a new machine, the invitation card shows the logo in black on a very dark background. (This used to invert to white and should have continued to do so.) 

![black_on_black](https://cloud.githubusercontent.com/assets/9855795/10273592/53e2ab8a-6ae7-11e5-8661-6a36cd76ada7.jpg)

**Comment by shana** [comment]
Unsure when this regressed, but definitely a regression.

**Comment by shana** [comment]
It only happens when switching themes. If VS is started with the dark theme, the logo is displayed with the correct colors:

<img width="340" alt="screen shot 2015-10-05 at 12 42 42 pm" src="https://cloud.githubusercontent.com/assets/310137/10278600/c7caf3e6-6b5e-11e5-912b-a5b6f2233231.png">

Same thing happens when going from dark to a light theme:

<img width="301" alt="screen shot 2015-10-05 at 12 40 15 pm" src="https://cloud.githubusercontent.com/assets/310137/10278606/d62cd4e0-6b5e-11e5-9da1-46c8f9011aee.png">

**Comment by artl93** [comment]
On first install, the theme hadn't been set yet. Once I logged in, the UI showed the blue theme, then switched to dark.

**Comment by shana** [comment]
@artl93 Ah, right. That theme change trigger from the profile also happens when you sign in to VS, if the theme doesn't match.
