### ISSUE TITLE
Reverting extension in VS2017 causes errors with Extensions & Updates manager

### ISSUE THREAD

**Issue by meaghanlewis** [github/VisualStudio#1206]
__Version__

- GitHub Extension for Visual Studio  version: ?
- Visual Studio version: VS2017

__What happened__

Steps to reproduce:
- In VS2017, go to Tools < Extensions and Updates and select GitHub extension.
- Select to Revert.
- Go through steps and finish revert
- Close VS
- Open VS after revert is complete
- Go to Tools < Extensions and Updates
- Error! And Extensions and Updates can't open
<img width="443" alt="screen shot 2017-08-29 at 2 25 50 pm" src="https://user-images.githubusercontent.com/10103121/29845248-f4c09d8e-8cc6-11e7-9443-8e930dd157c9.png">

After that I tried to install the latest vsix, and then saw this error:
<img width="440" alt="screen shot 2017-08-29 at 2 28 50 pm" src="https://user-images.githubusercontent.com/10103121/29845288-17fc4e06-8cc7-11e7-8a64-43ae0d5c999c.png">
(I can provide the install log if that helps.)

The good thing is that the extension seems usable, but I can no longer manage it- or any other extensions, because I can't view them. I've also tried this with multiple versions of the extension, but this continues to happen.

**Comment by shana** [comment]
@meaghanlewis Could you post the install log here?

@Michael-Eng Looks like we have another VS installer issue, could you help with this?

/cc @AArnott

**Comment by shana** [comment]
So looks like this is a VS installer bug. MS is working on it.

**Comment by meaghanlewis** [comment]
Here's the install log from this issue:
[install log post revert of GHfVS.txt](https://github.com/github/VisualStudio/files/1264170/install.log.post.revert.of.GHfVS.txt)

**Comment by Michael-Eng** [comment]
We're putting together the workaround instructions. Can you try these to see if they resolve the issue for you?

1.	Shutdown all instances of VS
2.	Update your state.json file
•	Backup your c:\programdata\Microsoft\VisualStudio\Packages\_Instances\[hashid]\state.json file
•	In an elevated command prompt, edit the state.json file and delete all *GitHub* entries in the file
3.	Delete the extension directory/directories that contain the GitHub extension. Since the GitHub extension installs to a random location, we need to find the folders
•	In an elevated command prompt, go to c:\program files (x86)\Microsoft\VisualStudio\[Community/Pro/Enterprise]\Common7\IDE\Extensions
•	Run “dir /s *GitHub*”
•	Delete the directories that contain the GitHub files
4.	Delete the extension cache files at c:\users\[username]\AppData\Local\Microsoft\VisualStudio\15.0[hashid]\Extensions\*.cache
5.	Restart VS and reinstall the GitHub extension

Thanks!

**Comment by meaghanlewis** [comment]
Hi @Michael-Eng, thanks for these steps!

They work, but I actually only need to do steps 1 and 2 to be able to manage my extensions again.

**Comment by Michael-Eng** [comment]
Thanks @meaghanlewis. Step #3 is required so that there aren't two copies of the GitHub extension installed (bad things will happen if we see more than one copy of the GitHub extension and try to load both) and #4 forces us to rescan all extensions. Thanks for verifying the steps.

The issue is fixed in 15.4. We have also posted these workaround steps here: [https://developercommunity.visualstudio.com/content/problem/102178/error-installing-github-extension.html](https://developercommunity.visualstudio.com/content/problem/102178/error-installing-github-extension.html)

**Comment by meaghanlewis** [comment]
Okay, got it @Michael-Eng. I'll keep these workaround steps handy until this issue is fixed 😄

**Comment by shana** [comment]
Thanks for all the help @Michael-Eng! I've updated the README and the website help section with a notice and links to the workarounds regarding this issue, hopefully we won't get a lot of users running into this before the fix is out 🤞

**Comment by shana** [comment]
# Update on how to bypass the Revert problem

A straightforward way of bypassing the "Revert" problem is to manually uninstall the extension on the command line:

1. Shutdown VS 2017
1. Open a `Developer Command Prompt for VS 2017` in administrator mode by right-clicking on the Start menu shortcut and selecting `Run as administrator`
1. run `vsixinstaller /uninstall:c3d3dc68-c977-411f-b3e8-03b0dccf7dfc` to uninstall the currently installed extension

After this is done, you can install the current version from the marketplace, or any previous version from our gallery feed:

1. Go to ***Tools*** / ***Options*** / ***Extensions and Updates***
1. Adding a new gallery with the name *GitHub* and url *https://visualstudio.github.com/releases/feed.rss*
1. The gallery will now be available from ***Extensions and Updates*** inside the ***Online*** or ***Updates*** tab and you can pick from the last 10 or so versions.

**Comment by toddhd** [comment]
vsixinstaller /uninstall:c3d3dc68-c977-411f-b3e8-03b0dccf7dfc says uninstall failed. I had already previously tried upgrading/reverting several times. What else can I try? Can I manually uninstall this?

**Comment by sguthals** [comment]
@grokys - do you know if @toddhd can manually uninstall if the uninstall command isn't working?

@toddhd - were you ever able to resolve this?
