### ISSUE TITLE
GitHub Extension for Visual Studio in Community Edition of VS does not respect .gitignore

### ISSUE THREAD

**Issue by jfren484** [github/VisualStudio#127]
I added *.Sensitive.config to my .gitignore file so that my connection strings would not be checked into github. On my work laptop, which has VS Professional 2015 and latest GitHub Extension, it correctly ignores Web.Sensitive.config. On my personal laptop, which has VS Community 2015 and latest GitHub Extension, it still lists Web.Sensitive.config in my Excluded changes instead of not listing it at all. It's been like this for several weeks, now, actually, so across several versions of the extension the behavior has remained the same.

**Comment by shiftkey** [comment]
Can you attach a screenshot of what you're seeing, as well as the rules defined in your .gitignore file?

I think this is related to the Git integration in Visual Studio (working with a local repository), rather than the GitHub extension (publishing to and cloning a repository from the GitHub server) but I'd like to confirm this before I go and bug them :grin:

**Comment by jfren484** [comment]
When I was preparing to take a screenshot I thought I'd try "undo-ing" the add of the file, and that removed it from the list of changes. Now it's not bugging me to add it again. So I think it was probably a defect that existed in a previous version but was fixed. Sorry to waste your time!

**Comment by shana** [comment]
@jfren484 It's a known bug in Visual Studio itself, where it gets confused when first loading a project with .gitignore entries and erroneously adds them to the excluded changes list instead of hiding them. The correct "fix" is indeed to just undo the excluded changes, like you just did. MS is aware of this and hopefully will fix it soon.
