### ISSUE TITLE
No Open/Link to GitHub Available 

### ISSUE THREAD

**Issue by ambroselittle** [github/VisualStudio#1291]
- GitHub Extension for Visual Studio  version: 2.3.4.54
- Visual Studio version: 15.4.2

**Repro**:
1. Open solution that is in a git repo from our GitHub Enterprise.
2. Open any code (.cs) file (or .config, for instance).
3. Right-click on any line to view the context menu.

**Expected**: See a GitHub -> menu that has an Open/Link to GitHub link that will take me to the corresponding line in the repo/branch that I'm on at the time.

**Actual**: No GitHub menu. 

**Notes**: I reported this to Phil Haack and he looped in Andreia Gaita on Twitter. She suggested I report this here. 

Will email logs.

**Comment by grokys** [comment]
Hi @ambroselittle,

Apologies for the delay. I've just tried this and indeed we seem to have a bug with Open/Link to GitHub on Enterprise instances.

The problem is at [this line](https://github.com/github/VisualStudio/blob/f3d489d5b5a12b2dab605cb023cd1439a93df4af/src/GitHub.VisualStudio/Menus/MenuBase.cs#L134): `repo.FullName` returns the repo name in the form `owner/name` and it's being compared with `ActiveRepo.Name` which returns just the repro name.

Sorry about that - we'll get a fix in for the next release!

**Comment by ambroselittle** [comment]
Awesome. Thanks!
