### ISSUE TITLE
Checked out status of PR doesn't update until refresh

### ISSUE THREAD

**Issue by jcansdale** [github/VisualStudio#1345]
- GitHub Extension for Visual Studio version: 2.3.7
- Visual Studio version: 2015

__What happened__ (with steps, logs and screenshots, if possible)

1. Open PR detail view from PR list
2. Click on `Checkout - branch-name` button
3. PR is checked out, but button doesn't update
4. Click refresh button on GitHub pane
5. Button updates to show `Local branch up to date`

Notes:
- This works fine on current live version (`v2.3.6.391`).
- This doesn't work on branch `fixes/testable-teserviceholder`.

@grokys any thoughts?

**Comment by grokys** [comment]
I think this was caused by https://github.com/github/VisualStudio/pull/1292. This PR also fixes a bug that we were relying on in `TeamExplorerServiceHolder`, in that it was previously firing `RepoChanged` when the _status_ of the repo were changed where it was meant to only be fired when _moving to a new repo_.

I suspect we'll need to add a `StatusChanged` signal or similar to `TeamExplorerServiceHolder`.
