### ISSUE TITLE
PR Details: Deleted file shouldn't show "Open ..." menu item

### ISSUE THREAD

**Issue by shana** [github/VisualStudio#1348]
If a file has been deleted in a PR and there are no local changes that add it back in some way, the context menu items related to opening that file in the solution don't do anything and should probably not be shown at all (or at least be disabled)

![image](https://user-images.githubusercontent.com/310137/33321743-0f020d82-d447-11e7-857d-79fe7784db6c.png)

**Comment by StanleyGoldman** [comment]
I am not able to reproduce this bug.

**Comment by StanleyGoldman** [comment]
@meaghanlewis could you confirm this for me?

**Comment by meaghanlewis** [comment]
@StanleyGoldman I just tried it out with Steven's SSO PR. When I am on master and just looking at the deleted files for the PR I see the same behavior as in the screenshot you shared.

When I actually check out the PR branch `feature/sso` I see what shana shows in the first screenshot and am able to Open File in Solution.

So, my question is if this bug was referring to being on the PR branch or not?
