### ISSUE TITLE
A git repository set up as a worktree may not be detected properly

### ISSUE THREAD

**Issue by shana** [github/VisualStudio#1457]
From a support ticket: 
> GitHub extension does not appear to support worktrees?? We I have a worktree created off of my main Git and the rest of Visual Studio recognizes it as part of a git repo etc, but the GitHub tab appears blank and says no repo found???

I'm not sure we've ever tested the specific scenario of working with a git repository that is set up as a worktree. We need to doublecheck that this works properly.

**Comment by meaghanlewis** [comment]
In VS2015, I'm unable to add a worktree as a local git repository and just get a message saying "No new repositories were found." I haven't found a successful way to use worktrees in VS2015, and am not sure there is much we can do about that.

In VS2017, I can add a worktree as a local git repository and do things like make changes and commit just fine. I don't seem to be able to publish the git repo as a GitHub repo because the repository does not have a remote. I think this is expected since the remote of the worktree is the same as the repository.
![screen shot 2018-02-06 at 2 05 25 pm](https://user-images.githubusercontent.com/10103121/35886963-aa3593f0-0b47-11e8-8439-482f8a5aad9b.png)

And the GitHub tab is never blank for me, but appears to show information for the main repository (020518) rather than the worktree (temp1). I wasn't able to create a pull request from this pane while being connected to my worktree repo.
![screen shot 2018-02-06 at 2 05 46 pm](https://user-images.githubusercontent.com/10103121/35887142-261ec04a-0b48-11e8-9350-3e742bc7981b.png)

**Comment by awbushnell** [comment]
@meaghanlewis I am now having problems with the GitHub extension from showing anything... On my local system, all I do is load Visual Studio 2017..  Open the project I am working on that is being version controlled via Git.  The Visual Studio Team Explorer properly sees it as a Git repo and shows me branch etc. information, but when I switch to the GitHub view, it simply displays:

![capture](https://user-images.githubusercontent.com/11314686/35980696-56271428-0cb9-11e8-8135-fe236ea0c608.PNG)

Notice in the image, GitHub empty, yet team explorer is properly showing Repo info...

Even clicking get started, just brings me to the team explorer view and nothing updates/happens.

**Comment by grokys** [comment]
@awbushnell what is the output of running `git remote -vv` in the repository?

**Comment by awbushnell** [comment]
@grokys  it looks correct, we are on GitHub enterprise and it spits the following 2 lines out:

origin [correcthttpspathtoourenterpriserepo] (fetch)
origin [correcthttpspathtoourenterpriserepo] (push)

**Comment by grokys** [comment]
@awbushnell ok this looks like a different issue to the worktree issue so migrating it to #1473.

**Comment by awbushnell** [comment]
@meaghanlewis @grokys Just as an FYI, but after signing out then signing back into our enterprise server with a personal access token I was able to generate, github view now seems to be properly populated etc.. Though I still do not see Images for the owners etc. as do on our github server, which I believe has already reported.

**Comment by meaghanlewis** [comment]
Closing this issue in favor of #1652
