### ISSUE TITLE
VS2017 crash when trying to compare two commits from history list

### ISSUE THREAD

**Issue by rafalowski** [github/VisualStudio#1460]
- GitHub Extension for Visual Studio  version: 2.4.0.1202
- Visual Studio version: 2017 Professional Version 15.5.5

After updating to the latest version visual studio crashes when trying two compare two commits
Repoduce:
1) Open a file in the text editor
2) Source Control -> View History
3) choose 2 commits from hostiry.
4) right click and compare

**Comment by jcansdale** [comment]
@rafalowski, Thanks for the report. We're hoping to get a fix for this out on Monday (see #1454).

Could you try installing the version linked here: https://github.com/github/VisualStudio/issues/1454#issuecomment-362677155

Could you confirm whether it resolves it on the same thread? Unfortunately this issue seems to be somewhat random (it didn't appear during our testing). The more confirmations we get the better!

**Comment by JMS-1** [comment]
Same Problem, .1219 works for me. Thanks.
