### ISSUE TITLE
Version 2.4.0.1202 of the GitHub extension for visual studio 2017 crashes when comparing changes

### ISSUE THREAD

**Issue by jficarapi** [github/VisualStudio#1461]
- GitHub Extension for Visual Studio  version: 2.4.0.1202
- Visual Studio version: Enterprise 2017 15.5.6

__What happened__ 
1. From solution explorer right click on a file with changes that has been previously pushed
2. Choose "Compare with Unmodified..." 
3. Observe Visual Studio crash and restart

**Comment by jcansdale** [comment]
@jficarapi, thanks for the report. We're hoping to get a fix for this out on Monday (see #1454).

Could you try installing the version linked here: #1454 (comment)

Could you confirm whether it resolves it on the same thread? Unfortunately this issue seems to be somewhat random (it didn't appear during our testing). The more confirmations we get the better!
