### ISSUE TITLE
VS doesnt want to push to 2fa github repo

### ISSUE THREAD

**Issue by Barsonax** [github/VisualStudio#1503]
As of today I cannot push to github anymore in visual studio and I get the following error (just logging in works):
```
Error encountered while pushing to the remote repository: Git failed with a fatal error.
HttpRequestException encountered.
   An error occurred while sending the request.
cannot spawn askpass: No such file or directory
could not read Username for 'https://github.com': terminal prompts disabled
Pushing to https://github.com/Barsonax/Pathfindax.git
```

Suspecting 2fa to be the cause of this but I cannot disable it because the organisation I belong to requires it.

EDIT: Tortoise git works with a personal access token but visual studio doesnt.

**Comment by meaghanlewis** [comment]
👋 @Barsonax.

Today GitHub turned off TLSV1.1 in order to permanently disable deprecation of several weak cryptographic standards. You could read more about that here: https://githubengineering.com/crypto-removal-notice/.

To fix this issue, you should upgrade to the latest version of Visual Studio, 15.5.7- which provides support for TLSV1.2. This update allows Git to connect to services that have deprecated support for TLSv1 and TLSv1.1.

You might also need to sign in (or sign out and then sign back in) using GitHub for Visual Studio.

**Comment by Barsonax** [comment]
Yup updating to 15.5.7 fixes it

**Comment by meaghanlewis** [comment]
Awesome, thanks!
