### ISSUE TITLE
[Feature request] Make "View Changes in Solution" the default when checked out

### ISSUE THREAD

**Issue by jcouv** [github/VisualStudio#1574]
"View changes in solution" seems always better than just "view changes", as it offers better navigation (GoToDefinition, QuickInfo, classification, etc).
I would propose that the default action for "double-clicking" on a file should be "view changes in solution" when the PR is checked out.

~~(As a side note, I noticed a few cases where GoToDefinition in a file opened with "view changes in solution" didn't work as expected, ie failed. I'll probably file an issue once I have more details)~~

I don't know if it's technically possible or easy, but I would propose to take this further and make opening any file that is part of the PR to open with "view changes in solution". This should apply when opening from the GitHub extension window, but also other file open events (GoToDefinition, GoToAll, open from Solution Explorer, etc).
If a file is part of the PR, and the PR is checked out, it should always open with the best view possible by default (ie with "view changes in solution").

A third part of this suggestion would be allowing comments to be added on a file opened with "Open file in solution", as long as that file is part of the PR. That view is very convenient for files that are added (no old version to diff against).

```
Microsoft Visual Studio Enterprise 2017 Preview
Version 15.7.0 Preview 1.0
VisualStudio.15.Preview/15.7.0-pre.1.0+27512.0

GitHub.VisualStudio   2.4.99.1998
```

Tagging @jcansdale 
Btw, thanks to the crew for the fantastic feature (PR review and check out).

**Comment by grokys** [comment]
@jcouv thanks for the suggestion! This is actually how the feature originally worked, but after working with it like this for a while, we found a few problems. There are actually 3 different comparisons that you can do on a PR when working in the IDE:

1. Compare with the commit at the head of the PR branch on GitHub
2. Compare with the commit at the head of the PR branch locally
3. Compare with the current working copy

We decided to go with 1 by default and 3 using a context menu because:

1. People found it confusing when the diff that we showed in VS was different to the diff on github.com
2. Leaving comments on diffs didn't work properly, because the code needs to be pushed to GitHub in order to be commented on

Longer-term, I would like to find a way to handle this better and allow switching between the 3 states listed above, and maybe allow comments to be stored locally until code is pushed to GitHub, but for the moment we think that giving the option to do 3 from a context menu is the best solution.

**Comment by jcansdale** [comment]
@jcouv,

> If I could offer a related suggestion: if you open the same view twice, it would be great if the first view could be re-used. I can file a separate issue if that helps.

If you could open a separate issue, that would be great. I think this is definitely needed.

At the moment if you start adding a comment and then open a new file, the tab with your comment on will be lost (along with the comment). I think we need to auto-persist tabs when a user starts adding a comment. It will therefore be important to navigate back to the original tab when the same file is opened!
