### ISSUE TITLE
The file modification status is not fully displayed.

### ISSUE THREAD

**Issue by liuyanchen1994** [github/VisualStudio#1584]
![image](https://user-images.githubusercontent.com/19524048/38344707-8f5f4596-38bd-11e8-80fc-dae91e50de2d.png)

**Comment by liuyanchen1994** [comment]
Vs update to 15.6.1 has no status icon.

**Comment by grokys** [comment]
Hi @liuyanchen1994 - is this in the Team Explorer window? (apologies, I can't read Chinese)

**Comment by liuyanchen1994** [comment]
![image](https://user-images.githubusercontent.com/19524048/38404275-6271fed2-399b-11e8-85bc-400a7d7e59f5.png)
![image](https://user-images.githubusercontent.com/19524048/38404295-80c70e18-399b-11e8-8688-9f9bf6b0660f.png)

**Comment by liuyanchen1994** [comment]
@grokys  Updated to vs15.6.1, this icon is sometimes displayed, sometimes not displayed.

**Comment by grokys** [comment]
Ah, ok, it's the solution explorer.

That's not part of GitHub for Visual Studio so unfortunately we can't help there. The best way to proceed would be to use the Report a Problem tool in VS so Microsoft can get diagnostics to figure out what's going on: https://docs.microsoft.com/en-us/visualstudio/ide/how-to-report-a-problem-with-visual-studio-2017

Closing this as I don't think we can help an more here. Thanks for getting in touch!

**Comment by BUAA-CFan** [comment]
I got the same problem in the solution center,too.
Sometimes these icons just disappear. And it seems that there is always no status icon in front of the folder in the solution center. It is so inconvenient to find all the changes and status of files in my solution, though i can find them after i choose to filter.
These two pics are status icons of Github extention and visual SVN for visual studio. 
![20180726151048](https://user-images.githubusercontent.com/17959229/43247553-9ca9d2c0-90e7-11e8-88f4-436b308c69f1.png)
![20180726151141](https://user-images.githubusercontent.com/17959229/43247555-9ce326d8-90e7-11e8-9c40-ff5557370747.png)

I don't think if the icon appears or what rule they follow when appears is decided by visual studio because icons in these two pics are not the same apparently. There should be some way to control them.
At last, I hope to see changes in the future.
Thanks anyway!
