### ISSUE TITLE
Incorrect UI while using a non-GitHub repo

### ISSUE THREAD

**Issue by Nettsentrisk** [github/VisualStudio#164]
I use this plugin for repos both on GitHub and our company's own Git repo.

When using the company repo, and I go to Synchronization, it gives me the following warning at the top: "You are not logged in to [server address], so certain git operations may fail. Login now"

The login now assumes I want to log into GitHub Enterprise, although I'm already logged in to my company's git server/repo. I can commit and everything to the company repo just fine.

So why is this message claiming otherwise? Why is it trying to get me to log in to GitHub Enterprise for a non-GitHub URL/server?

It also shows the company git server repo listed under GitHub on the Home tab, and it shows a bunch of GitHub-specific functionality under the Project toggle, like Pulse and Graphs, even though it's not a GitHub repo.

**Comment by Nettsentrisk** [comment]
It also shows the company git server repo listed under GitHub on the Home tab, and it shows a bunch of GitHub-specific functionality under the Project toggle, like Pulse and Graphs, even though it's not a GitHub repo.

**Comment by shana** [comment]
Thanks for the report. It looks like the logic for determining whether the server is a GitHub server or not is getting a false positive on your server. It's hard to tell whether a remote with a non github.com url is an enterprise server or not, because when you're not logged in on an enterprise instance, the likely response to a GitHub API request is going to be similar to what you get when you try to call an API on a non-GitHub server.

The extra information you're seeing in the UI is calculated locally because it thinks the remote is an enterprise github instance. It is just for informational purposes (albeit incorrect in this case) and doesn't affect any git or other operations in Visual Studio, so you don't have to worry about that having any side effects other than showing (annoying) messages and extra buttons.

We'll get working on a fix for this and update the issue when it's out.

**Comment by OsirisTerje** [comment]
I see the same when logged in to a TFS (on-premises) git repository, and I would assume it should be possible to see the difference between a TFS git instance and a github instance, right ?

**Comment by shana** [comment]
@OsirisTerje I don't believe I said it wasn't possible to tell the difference, I merely said that the current code is giving a false positive on certain non-GitHub instances. Obviously your on-premises git server is similarly being misdetected.

**Comment by OsirisTerje** [comment]
@shana Ok :-)  If you need some fiddler trace or whatever, just ping.

**Comment by shana** [comment]
@OsirisTerje Actually... if you could do "curl -vv https://your-git-server/site/sha" on a command line and gist the result (or with a browser and Fiddler it), that would be great! Redact whatever you need, I just want to see the http status code and the headers it returns to you (the code right now is being overly naive, I need to be more specific about parsing responses)

**Comment by shana** [comment]
(the "site/sha" should be exactly that string, just plug in your git instance base url)

**Comment by OsirisTerje** [comment]
It returns this:  https://gist.github.com/OsirisTerje/48b62682d6df994276f2 
Is this what you're looking for ?

**Comment by OsirisTerje** [comment]
There are two responses, one if authorized (404), and one if not (401).  Added the latter too to the gist above

**Comment by shana** [comment]
@OsirisTerje That's perfect, thanks!

**Comment by shana** [comment]
A fix for this issue will be included in release 1.0.16.1, which will be out before Monday. 
If you could test the fix and let me know how it goes, that would be great! The vsix package is available from https://github.com/github/VisualStudio/releases/tag/v1.0.16.1
