### ISSUE TITLE
Changes to Solution outside of the IDE are not prompted for reload

### ISSUE THREAD

**Issue by mwpowellhtx** [github/VisualStudio#1657]
Used to be that I could make a change to my Solution outside the IDE, tweak a path, something like that, and the IDE would discover that and prompt me to reload. This is not happening in the current 2017 IDE.

**Comment by jcansdale** [comment]
Hi @mwpowellhtx,

This is the GitHub for Visual Studio extension repository, not general issues for Visual Studio / Team Explorer. I'll see if I can help anyway.

I wonder if the not prompting to reload might be by design? I remember seeing this tweet:
https://twitter.com/davkean/status/992016165915344896

@davkean is probably a good person to ask about it.

Please report back here if you find out what's going on.

**Comment by mwpowellhtx** [comment]
Thanks for the clarification. Yes that helped. Hopefully I got the issue filed correctly.
