### ISSUE TITLE
Error while clicking on Sync

### ISSUE THREAD

**Issue by laurentkempe** [github/VisualStudio#1668]
Working on the #1667 I tried from Visual Studio to click on Sync to get one update of the sub modules

![image](https://user-images.githubusercontent.com/272612/40112121-4d20e348-5905-11e8-84fc-a98fe82dbe02.png)

Here is the error in text

> Synchronizing submodule url for 'script'
Synchronizing submodule url for 'submodules/akavache'
Synchronizing submodule url for 'submodules/octokit.net'
Synchronizing submodule url for 'submodules/reactiveui'
Synchronizing submodule url for 'submodules/splat'
Cloning into 'C:/Users/laure/projects/GithubVisualStudio/script'...
Host key verification failed.
fatal: Could not read from remote repository.

>Please make sure you have the correct access rights
and the repository exists.
fatal: clone of 'git@github.com:github/VisualStudioBuildScripts' into submodule path 'C:/Users/laure/projects/GithubVisualStudio/script' failed
Failed to clone 'script'. Retry scheduled
Cloning into 'C:/Users/laure/projects/GithubVisualStudio/script'...
Host key verification failed.
fatal: Could not read from remote repository.

> Please make sure you have the correct access rights
and the repository exists.
fatal: clone of 'git@github.com:github/VisualStudioBuildScripts' into submodule path 'C:/Users/laure/projects/GithubVisualStudio/script' failed
Failed to clone 'script' a second time, aborting

Any clue what could be the problem?

**Comment by jcansdale** [comment]
Oops, this is unfortunate. The submodule that needed to be updated in this case was `akavache`. You don't have access to `github/VisualStudioBuildScripts` because it's private to GitHub. All it means is that external developers need to manually populate the `src/GitHub.Api/ApiClientConfiguration_User.cs` key.

Don't worry about this unless you're experiencing other issues with it.

**Comment by laurentkempe** [comment]
@grokys I think I did, but I have a doubt now! I will do it again to see

**Comment by laurentkempe** [comment]
@grokys I did a new checkout and followed the process and still get the same error!

**Comment by jcansdale** [comment]
I think this is a bit of a special case. It happens when a user does a Sync submodules on a repository that includes a submodule they don't have access to (in this case the `script` submodule).

I'm not sure what it would be best to do in this situation. The default error includes the following:

![image](https://user-images.githubusercontent.com/11719160/43769098-e140174e-9a30-11e8-9c26-b265e0804d9c.png)

This error is correct and includes a reasonable suggestion.

Since this is an edge case and the error is correct, I'm going to close. Please let me know if you think I'm doing too hasty!
