### ISSUE TITLE
Corrupt extension cache and missing MEF exports

### ISSUE THREAD

**Issue by jcansdale** [github/VisualStudio#1859]
- GitHub Extension for Visual Studio version: 2.5.4.3349 (probably any)
- Visual Studio version: 15.6.6, 15.7.5, 15.7.3, 15.7.5, 15.7.5, 15.7.6, 5.8 Preview 5, 5.8 Preview 4

We have been seeing many issues that involve missing MEF components, for example:

- #1826 GitHub Extension broken with VS 15.7.6 
- #1810 SetSite failed for the package [GitHubPackage], VS 15.8 Preview 4/5 
- #1812 Error On Project Load 

### Symptoms

These tend to manifest themselves as follows on the GitHub pane:
```
System.InvalidOperationException: Could not locate any instances of contract GitHub.Services.ITeamExplorerServiceHolder.
   at GitHub.VisualStudio.GitHubServiceProvider.GetService(Type serviceType) in C:\projects\visualstudio\src\GitHub.VisualStudio\Services\GitHubServiceProvider.cs:line 147
   at GitHub.VisualStudio.GitHubServiceProvider.GetService[T]() in C:\projects\visualstudio\src\GitHub.VisualStudio\Services\GitHubServiceProvider.cs:line 153
   at GitHub.VisualStudio.UI.GitHubPane.<InitializeAsync>d__12.MoveNext() in C:\projects\visualstudio\src\GitHub.VisualStudio\UI\GitHubPane.cs:line 98
```

Or like this when opening a solution that's hosted on GitHub:

![image](https://user-images.githubusercontent.com/11719160/43982975-2e10d5ce-9cf0-11e8-837b-9c9c562aa1d1.png)

With an entry in the ActivityLog:
```xml
<description>
SetSite failed for package [GitHubPackage]
  Source: 'System.ComponentModel.Composition'
  Description: No exports were found that match the constraint:
 ContractName=GitHub.Commands.IOpenFromUrlCommand
 RequiredTypeIdentity=GitHub.Commands.IOpenFromUrlCommand
</description>
```

### What's going on

*Update from Daniel Griffen @dgriffen on [Gitter](https://gitter.im/Microsoft/extendvs?at=5b7739225921214124814450).*

> @jcansdale I was able to reproduce this locally! I've figured out the issue and am working on how to fix it on our end or provide you with a workaround.
> @jcansdale there is a slight issue where the target version is getting the incorrect version of the running VS process and therefore excluding both your teamfoundation mef assets.
> The commit that added that to your extension was here: https://github.com/github/VisualStudio/commit/c9703cd2a284840474b191449c52bb67b181a5e4#diff-f5cce9abffe08468ca7c1c1cd08cc17f
> @jcansdale the bug is that sometimes servicehub's version is used which is not tied directly to the VS version (currently, its ~1.3 I think).

This doesn't appear to be caused by a specific version of GitHub for Visual Studio or MEF component, but seems to be a ~~random corruption of the extension cache~~ see above.

Simply clearing the MEF component cache or running `devenv.exe /updateConfiguration` won't repair the extension cache (which is usually what resolves missing MEF components).

#### Clearing the extension *and* MEF caches

The quickest way is to delete the following file and directory (where `15.0_xxxxxxxx` corresponds to a particular instance of Visual Studio):
```
%USERPROFILE%\AppData\Local\Microsoft\VisualStudio\15.0_xxxxxxxx\Extensions\extensions.en-US.cache
%USERPROFILE%\AppData\Local\Microsoft\VisualStudio\15.0_xxxxxxxx\ComponentModelCache
```

Deleting `extensions.en-US.cache` causes the extension cache to be recreated and deleting the `ComponentModelCache` directory clears the MEF component cache.

#### Reinstalling the extension

The alternative way is to uninstall and then re-install GitHub for Visual Studio.

This can be error prone when done manually because the `VSIX Installer` often appears behind other windows. It's easy to think the uninstall has completed when it hasn't even started. Perhaps we could provide a script for doing this?

### Automatic detection

Missing MEF components would be easy to detect during our package initialization. The `package did not load correctly` dialog only appears because we don't handle an exception in our package initialization. At the very least we could point users to instructions on how to repair their extension cache.

### Automatic repair

It's easier to find the relevant cache files from inside an instance of Visual Studio that it is to find the correct instance-Guid and paths from an external script. It would be straightforward to detect suspected cache corruption and offer to perform an automatic repair.

**Comment by vaindil** [comment]
I came here from #1810. I did not have a file or folder called `ComponentModelCache` in the `Extensions` folder, so I assumed it was the folder one level up (at `VisualStudio\15.0_xxxxx\ComponentModelCache`). I renamed both that folder and the `extensions.en-US.cache` file, no error popup happened. I restarted VS just to check, and the popup still did not happen.

Looks like this fixes the problem. Let me know if you'd like me to test anything else. Thanks!

**Comment by vaindil** [comment]
I had to reboot my computer for something unrelated, after the reboot I'm getting the popup again.

**Comment by apobekiaris** [comment]
same here reboot restored the bad behaviour

**Comment by meaghanlewis** [comment]
Thanks for letting us know @vaindil and @apobekiaris. We're going to have to look into this issue more to understand what is going wrong.

**Comment by dgriffen** [comment]
@vaindil @apobekiaris Can I get some extra information from you to try and diagnose this problem?
- what version of VS are you running
- what extensions/workloads do you have installed?
- how did you install the github extension? marketplace or through the VS installer?

I can't reproduce this issue locally so I'm trying to eliminate any variables I can.

**Comment by vaindil** [comment]
@dgriffen Here's the output from doing Help > About Visual Studio > Copy Info. I believe I originally installed the GitHub extension from the marketplace, but I'm not certain of that.

```
Microsoft Visual Studio Professional 2017 Preview
Version 15.8.0 Preview 5.0
VisualStudio.15.Preview/15.8.0-pre.5.0+27924.0
Microsoft .NET Framework
Version 4.7.03056

Installed Version: Professional

AddNuSpecCommand Extension   1.0
AddNuSpecCommand Visual Stuido Extension Detailed Info

ASP.NET and Web Tools 2017   15.8.05039.0
ASP.NET and Web Tools 2017

ASP.NET Core Razor Language Services   15.8.31590
Provides languages services for ASP.NET Core Razor.

ASP.NET Web Frameworks and Tools 2017   5.2.60618.0
For additional information, visit https://www.asp.net/

Azure App Service Tools v3.0.0   15.8.05023.0
Azure App Service Tools v3.0.0

Browser Reload on Save   1.0.25
A Visual Studio extension for ASP.NET projects that leverages Browser Link to to reload all connected browsers when files are saved in Visual Studio.

C# Tools   2.9.0-beta8-63119-10
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Clear MEF Component Cache   1.4
Clears the Visual Studio MEF component cache to fix issues with cache corruption.

CodeMaid   10.5.119
CodeMaid is an open source Visual Studio extension to cleanup and simplify our C#, C++, F#, VB, PHP, PowerShell, R, JSON, XAML, XML, ASP, HTML, CSS, LESS, SCSS, JavaScript and TypeScript coding.

Common Azure Tools   1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

GitClientVSPackage Extension   1.0
GitClientVSPackage Visual Studio Extension Detailed Info

GitHub.VisualStudio   2.5.5.3618
A Visual Studio Extension that brings the GitHub Flow into Visual Studio.

HTML Tools   1.0.3
Productivity tools for the HTML editor

I Hate #Regions   1.0
Regions Suck.  You need this.

IntelliCode Extension   1.0
IntelliCode Extension

IntellicodePackage Extension   1.0
IntellicodePackage Visual Studio Extension Detailed Info

JavaScript Language Service   2.0
JavaScript Language Service

JavaScript Project System   2.0
JavaScript Project System

Merq   1.1.38 (5b3c069)
Command Bus, Event Stream and Async Manager for Visual Studio extensions.

Microsoft Continuous Delivery Tools for Visual Studio   0.4
Simplifying the configuration of continuous build integration and continuous build delivery from within the Visual Studio IDE.

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Microsoft Library Manager   1.0
Install client-side libraries easily to any web project

Microsoft MI-Based Debugger   1.0
Provides support for connecting Visual Studio to MI compatible debuggers

Microsoft Visual Studio Tools for Containers   1.1
Develop, run, validate your ASP.NET Core applications in the target environment. F5 your application directly into a container with debugging, or CTRL + F5 to edit & refresh your app without having to rebuild the container.

Mono Debugging for Visual Studio   4.11.7-pre (8955b2a)
Support for debugging Mono processes with Visual Studio.

Node.js Tools   1.4.20716.1 Commit Hash:d70b330cd8f6dec8cbbd5e18c100eb847dfc22ef
Adds support for developing and debugging Node.js apps in Visual Studio

NuGet Package Manager   4.6.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit http://docs.nuget.org/.

Open Command Line   2.1.216
Opens a command line at the root of the project. Support for all consoles such as CMD, PowerShell, Bash etc. Provides syntax highlighting, Intellisense and execution of .cmd and .bat files.

ProjectServicesPackage Extension   1.0
ProjectServicesPackage Visual Studio Extension Detailed Info

ResourcePackage Extension   1.0
ResourcePackage Visual Studio Extension Detailed Info

ResourcePackage Extension   1.0
ResourcePackage Visual Studio Extension Detailed Info

SQL Server Data Tools   15.1.61807.14020
Microsoft SQL Server Data Tools

TypeScript Tools   15.8.20716.2001
TypeScript Tools for Microsoft Visual Studio

Viasfora   4.1.182
Add color to your Visual Studio editor!

Visual Basic Tools   2.9.0-beta8-63119-10
Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Visual F# Tools 10.2 for F# 4.5   15.8.0.0.  Commit Hash: 816a5a25b4a8bea43b72eb41bb55589d7605a1cd.
Microsoft Visual F# Tools 10.2 for F# 4.5

Visual Studio Code Debug Adapter Host Package   1.0
Interop layer for hosting Visual Studio Code debug adapters in Visual Studio

Visual Studio Tools for Containers   1.0
Visual Studio Tools for Containers

VisualStudio.Mac   1.0
Mac Extension for Visual Studio

VSColorOutput   2.5.1
Color output for build and debug windows - http://mike-ward.net/vscoloroutput

Xamarin   4.11.0.731 (d15-8@1b61b3b4e)
Visual Studio extension to enable development for Xamarin.iOS and Xamarin.Android.

Xamarin Designer   4.14.218 (79f535bdd)
Visual Studio extension to enable Xamarin Designer tools in Visual Studio.

Xamarin Live Reload   0.3.27 (remotes/origin/dev@207abf7)
Provides live reload capabilities for Xamarin XAML.

Xamarin Templates   1.1.104 (12ebed1)
Templates for building iOS, Android, and Windows apps with Xamarin and Xamarin.Forms.

Xamarin.Android SDK   9.0.0.17 (HEAD/dfb09269d)
Xamarin.Android Reference Assemblies and MSBuild support.

Xamarin.iOS and Xamarin.Mac SDK   11.14.0.11 (61d20a8)
Xamarin.iOS and Xamarin.Mac Reference Assemblies and MSBuild support.
```

**Comment by apobekiaris** [comment]
Microsoft Visual Studio Enterprise 2017 
Version 15.8.0
VisualStudio.15.Release/15.8.0+28010.0
Microsoft .NET Framework
Version 4.7.03056

Installed Version: Enterprise

Architecture Diagrams and Analysis Tools   00369-60000-00001-AA601
Microsoft Architecture Diagrams and Analysis Tools

Visual C++ 2017   00369-60000-00001-AA601
Microsoft Visual C++ 2017

ASP.NET and Web Tools 2017   15.8.05067.0
ASP.NET and Web Tools 2017

ASP.NET Core Razor Language Services   15.8.31590
Provides languages services for ASP.NET Core Razor.

ASP.NET Web Frameworks and Tools 2017   5.2.60618.0
For additional information, visit https://www.asp.net/

Azure App Service Tools v3.0.0   15.8.05023.0
Azure App Service Tools v3.0.0

BusinessObjectEditor   1.0
Information about my package

C# Tools   2.9.0-beta8-63208-01
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Clear MEF Component Cache   1.4
Clears the Visual Studio MEF component cache to fix issues with cache corruption.

Common Azure Tools   1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

ConvertToDevExtremeCommand Extension   1.0
ConvertToDevExtremeCommand Visual Studio Extension Detailed Info

DevExpress.DeploymentTool   1.0
A useful tool for deploying DevExpress assemblies.

DevExpress.ExpressApp.Design.DynamicPackage   1.0
DevExpress VSIX Package

DevExpress.ExpressApp.DesignPackage   1.0
DevExpress VSIX Package

DevExpress.Win.LayoutAssistant Extension   1.0
DevExpress.Win.LayoutAssistant Visual Studio Extension Detailed Info

DevExpress.XtraReports.RepxPackage   10.0
Showing the editor for REPX files.

DevExtreme.Design   17.1.7
DevExtreme Visual Studio integration package

GitHub.VisualStudio   2.5.5.3618
A Visual Studio Extension that brings the GitHub Flow into Visual Studio.

JavaScript Language Service   2.0
JavaScript Language Service

JavaScript Project System   2.0
JavaScript Project System

JetBrains ReSharper Ultimate 2018.1.4    Build 112.0.20180731.142027
JetBrains ReSharper Ultimate package for Microsoft Visual Studio. For more information about ReSharper Ultimate, visit http://www.jetbrains.com/resharper. Copyright © 2018 JetBrains, Inc.

JustDecompilePackage2017 Extension   1.0
JustDecompilePackage2017 Visual Studio Extension Detailed Info

Merq   1.1.38 (5b3c069)
Command Bus, Event Stream and Async Manager for Visual Studio extensions.

Microsoft Azure Tools   2.9
Microsoft Azure Tools for Microsoft Visual Studio 2017 - v2.9.10730.2

Microsoft Continuous Delivery Tools for Visual Studio   0.4
Simplifying the configuration of continuous build integration and continuous build delivery from within the Visual Studio IDE.

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Microsoft Library Manager   1.0
Install client-side libraries easily to any web project

Microsoft MI-Based Debugger   1.0
Provides support for connecting Visual Studio to MI compatible debuggers

Microsoft Visual C++ Wizards   1.0
Microsoft Visual C++ Wizards

Microsoft Visual Studio Tools for Containers   1.1
Develop, run, validate your ASP.NET Core applications in the target environment. F5 your application directly into a container with debugging, or CTRL + F5 to edit & refresh your app without having to rebuild the container.

Microsoft Visual Studio VC Package   1.0
Microsoft Visual Studio VC Package

MLGen Package Extension   1.0
MLGen Package Visual Studio Extension Detailed Info

Mono Debugging for Visual Studio   4.11.7-pre (8955b2a)
Support for debugging Mono processes with Visual Studio.

NuGet Package Manager   4.6.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit http://docs.nuget.org/.

ProjectServicesPackage Extension   1.0
ProjectServicesPackage Visual Studio Extension Detailed Info

ResourcePackage Extension   1.0
ResourcePackage Visual Studio Extension Detailed Info

ResourcePackage Extension   1.0
ResourcePackage Visual Studio Extension Detailed Info

SQL Server Data Tools   15.1.61808.07020
Microsoft SQL Server Data Tools

TestDriven.Net   4.1-Alpha
Zero friction testing for Visual Studio

TypeScript Tools   15.8.20801.2001
TypeScript Tools for Microsoft Visual Studio

Visual Basic Tools   2.9.0-beta8-63208-01
Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Visual F# Tools 10.2 for F# 4.5   15.8.0.0.  Commit Hash: c55dd2c3d618eb93a8d16e503947342b1fa93556.
Microsoft Visual F# Tools 10.2 for F# 4.5

Visual Studio Code Debug Adapter Host Package   1.0
Interop layer for hosting Visual Studio Code debug adapters in Visual Studio

Visual Studio Tools for CMake   1.0
Visual Studio Tools for CMake

Visual Studio Tools for Containers   1.0
Visual Studio Tools for Containers

Visual Studio Tools for Universal Windows Apps   15.0.28010.00
The Visual Studio Tools for Universal Windows apps allow you to build a single universal app experience that can reach every device running Windows 10: phone, tablet, PC, and more. It includes the Microsoft Windows 10 Software Development Kit.

VisualStudio.Mac   1.0
Mac Extension for Visual Studio

VSPackage Extension   1.0
VSPackage Visual Studio Extension Detailed Info

Xamarin   4.11.0.732 (d15-8@33e83e124)
Visual Studio extension to enable development for Xamarin.iOS and Xamarin.Android.

Xamarin Designer   4.14.218 (79f535bdd)
Visual Studio extension to enable Xamarin Designer tools in Visual Studio.

Xamarin Templates   1.1.113 (e1d02a7)
Templates for building iOS, Android, and Windows apps with Xamarin and Xamarin.Forms.

Xamarin.Android SDK   9.0.0.18 (HEAD/3d8a28f1a)
Xamarin.Android Reference Assemblies and MSBuild support.

Xamarin.iOS and Xamarin.Mac SDK   11.14.0.13 (373c313)
Xamarin.iOS and Xamarin.Mac Reference Assemblies and MSBuild support.

XtraReports package   1.0
XtraReports package

**Comment by apobekiaris** [comment]
i think I got mine from previous github issue

**Comment by milanc** [comment]
I have updated my VS yesterday to 15.8.0 had no issues.
This morning I have updated "Project File Tools" extension and this error popped up again.

Using option to revert to previous version (2.5.2.2500) helped and extension was fixed.
After that I've run the update to 2.5.4.3349 (which was originally there) and all works fine.

**Comment by jcansdale** [comment]
*Update from Daniel Griffen @dgriffen on [Gitter](https://gitter.im/Microsoft/extendvs?at=5b7739225921214124814450).* I've added this to issue the description.

**Comment by jcansdale** [comment]
@vaindil, @apobekiaris, @milanc thanks for the reports everyone!

I'm back from holiday and have a new PR (#1875) with a fix.

This time I'm pretty optimistic that we understand what's going on and the fix will resolve the issue. You can find the .vsix here:
https://ci.appveyor.com/api/buildjobs/hrha4uj9rlxo2wdq/artifacts/2.5.5.3912%2FGitHub.VisualStudio.vsix

We're getting very close to a new release, so any reports, positive or negative would be much appreciated. If you could comment on the PR itself (#1875) that would be great!

**Comment by jcansdale** [comment]
@vaindil,

> I had to reboot my computer for something unrelated, after the reboot I'm getting the popup again.

Interesting. I wonder if that points towards the automatic updates scheduled task?

![image](https://user-images.githubusercontent.com/11719160/44593903-9dec4f00-a7bc-11e8-8aeb-1a9ace152d5e.png)

What do you think @dgriffen?

**Comment by dgriffen** [comment]
That task invokes devenv directly so it will use the correct version of VS. My guess is that the task had an issue running /updateConfiguration so the next time VS launched it had to rebuild its cache.

**Comment by aravindk777** [comment]
Not sure if this is the right forum for the same issue as i see it as closed but it doesnt look to be so. Nor that i could get to see a solution discussed. 

so, i have the VS 2017 on Windows 7. I recently updated the Github extension for VS from marketplace with the current VS version. Info below:
Microsoft Visual Studio Enterprise 2017 
Version 15.8.5
VisualStudio.15.Release/15.8.5+28010.2036
Microsoft .NET Framework
Version 4.6.01590

Installed Version: Enterprise

Microsoft Visual Studio Tools for Applications 2017   00369-90253-49770-AA943
Microsoft Visual Studio Tools for Applications 2017

Application Insights Tools for Visual Studio Package   8.13.10627.1
Application Insights Tools for Visual Studio

ASP.NET and Web Tools 2017   15.8.05085.0
ASP.NET and Web Tools 2017

ASP.NET Core Razor Language Services   15.8.31590
Provides languages services for ASP.NET Core Razor.

ASP.NET Web Frameworks and Tools 2012   4.0.30625.0
For additional information, visit https://www.asp.net/

ASP.NET Web Frameworks and Tools 2017   5.2.60618.0
For additional information, visit https://www.asp.net/

Azure App Service Tools v3.0.0   15.8.05023.0
Azure App Service Tools v3.0.0

Azure Data Lake Node   1.0
This package contains the Data Lake integration nodes for Server Explorer.

Azure Data Lake Tools for Visual Studio   2.3.3000.2
Microsoft Azure Data Lake Tools for Visual Studio

Azure Functions and Web Jobs Tools   15.8.05023.0
Azure Functions and Web Jobs Tools

Azure Stream Analytics Tools for Visual Studio   2.3.3000.2
Microsoft Azure Stream Analytics Tools for Visual Studio

C# Tools   2.9.0-beta8-63208-01
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Common Azure Tools   1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

GitHub.VisualStudio   2.5.6.4958
A Visual Studio Extension that brings the GitHub Flow into Visual Studio.

JavaScript Language Service   2.0
JavaScript Language Service

JetBrains ReSharper Ultimate 2018.2.3   Build 182.0.20180912.70621
JetBrains ReSharper Ultimate package for Microsoft Visual Studio. For more information about ReSharper Ultimate, visit http://www.jetbrains.com/resharper. Copyright © 2018 JetBrains, Inc.

Microsoft Azure HDInsight Azure Node   2.3.3000.2
HDInsight Node under Azure Node

Microsoft Azure Hive Query Language Service   2.3.3000.2
Language service for Hive query

Microsoft Azure Stream Analytics Language Service   2.3.3000.2
Language service for Azure Stream Analytics

Microsoft Azure Stream Analytics Node   1.0
Azure Stream Analytics Node under Azure Node

Microsoft Azure Tools   2.9
Microsoft Azure Tools for Microsoft Visual Studio 2017 - v2.9.10730.2

Microsoft Continuous Delivery Tools for Visual Studio   0.4
Simplifying the configuration of Azure DevOps pipelines from within the Visual Studio IDE.

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Microsoft Library Manager   1.0
Install client-side libraries easily to any web project

Microsoft MI-Based Debugger   1.0
Provides support for connecting Visual Studio to MI compatible debuggers

Microsoft Visual Studio Tools for Containers   1.1
Develop, run, validate your ASP.NET Core applications in the target environment. F5 your application directly into a container with debugging, or CTRL + F5 to edit & refresh your app without having to rebuild the container.

NuGet Package Manager   4.6.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit http://docs.nuget.org/.

Project   1.0
Information about my package

ProjectServicesPackage Extension   1.0
ProjectServicesPackage Visual Studio Extension Detailed Info

Redgate ReadyRoll   1.17.18155.10346
Extend DevOps processes to your SQL Server databases and safely automate database deployments.

Visit https://www.red-gate.com/readyroll for more information.

Copyright (C) 2011 Red Gate Software Ltd. All rights reserved.

This software contains components from Component Owl.
SQL Server is a registered trademark of Microsoft Corporation.
Visual Studio is a registered trademark of Microsoft Corporation.

ReadyRoll contains code from the following open source software:

NuGet https://www.nuget.org/
SQL LocalDB Wrapper https://github.com/martincostello/sqllocaldb
Autofac https://autofac.org/
Json.NET https://json.net/
MahApps.Metro http://mahapps.com/
SemVer https://github.com/maxhauser/semver
Log4Net http://logging.apache.org/log4net/
StringTemplate https://github.com/antlr/stringtemplate4
Extended WPF Toolkit https://wpftoolkit.codeplex.com/
Code InfoBox VSX http://www.codeproject.com/Articles/55196/Code-InfoBox-Visual-Studio-Extension-VSX
OctoPack https://github.com/OctopusDeploy/OctoPack
SQLite https://sqlite.org/

This product contains icons from http://www.visualpharm.com distributed under a free backlink license.

For license details or other notices relating to the above software, please see NOTICE.TXT and EULA.rtf in the ReadyRoll application folder.
    

Redgate SQL Prompt   9.3.0.6627
Write, format, and refactor SQL effortlessly

ResourcePackage Extension   1.0
ResourcePackage Visual Studio Extension Detailed Info

ResourcePackage Extension   1.0
ResourcePackage Visual Studio Extension Detailed Info

Snapshot Debugging Extension   1.0
Snapshot Debugging Visual Studio Extension Detailed Info

SQL Server Analysis Services   14.0.1016.285
Microsoft SQL Server Analysis Services Designer 
Version 14.0.1016.285

SQL Server Data Tools   15.1.61808.07020
Microsoft SQL Server Data Tools

SQL Server Integration Services   
Microsoft SQL Server Integration Services Designer
Version 14.0.3002.113

SQL Server Reporting Services   14.0.1016.285
Microsoft SQL Server Reporting Services Designers 
Version 14.0.1016.285

SsmsVsIntegration   1.0
Information about my package

ToolWindowHostedEditor   1.0
Hosting json editor into a tool window

TypeScript Tools   15.8.20822.2001
TypeScript Tools for Microsoft Visual Studio

Visual Basic Tools   2.9.0-beta8-63208-01
Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Visual F# Tools 10.2 for F# 4.5   15.8.0.0.  Commit Hash: 55a3dc3231c95c77f81ee53f7d29152029da7408.
Microsoft Visual F# Tools 10.2 for F# 4.5

Visual Studio Code Debug Adapter Host Package   1.0
Interop layer for hosting Visual Studio Code debug adapters in Visual Studio

Visual Studio Tools for Containers   1.0
Visual Studio Tools for Containers
---
Since then, i am getting the error. I tried clearing the cache from %appdata% settings etc, but like https://github.com/github/VisualStudio/issues/1859#issuecomment-412916074 said, it pops up after i restart. The only thing i havent done is update my VS version to latest from 15.8.5 to 15.8.6 (as of today). 

either i have to remove the Github extn or have to see how best i can go back to previous version or try update my VS and see if that may solve. 

Can someone point me to the solution what was done or what needs to be done to solve this?

**Comment by aravindk777** [comment]
> 
> 
> Not sure if this is the right forum for the same issue as i see it as closed but it doesnt look to be so. Nor that i could get to see a solution discussed.
> 
> so, i have the VS 2017 on Windows 7. I recently updated the Github extension for VS from marketplace with the current VS version. Info below:
> Microsoft Visual Studio Enterprise 2017
> Version 15.8.5
> VisualStudio.15.Release/15.8.5+28010.2036
> Microsoft .NET Framework
> Version 4.6.01590
> 
> Installed Version: Enterprise
> 
> Microsoft Visual Studio Tools for Applications 2017 00369-90253-49770-AA943
> Microsoft Visual Studio Tools for Applications 2017
> 
> Application Insights Tools for Visual Studio Package 8.13.10627.1
> Application Insights Tools for Visual Studio
> 
> ASP.NET and Web Tools 2017 15.8.05085.0
> ASP.NET and Web Tools 2017
> 
> ASP.NET Core Razor Language Services 15.8.31590
> Provides languages services for ASP.NET Core Razor.
> 
> ASP.NET Web Frameworks and Tools 2012 4.0.30625.0
> For additional information, visit https://www.asp.net/
> 
> ASP.NET Web Frameworks and Tools 2017 5.2.60618.0
> For additional information, visit https://www.asp.net/
> 
> Azure App Service Tools v3.0.0 15.8.05023.0
> Azure App Service Tools v3.0.0
> 
> Azure Data Lake Node 1.0
> This package contains the Data Lake integration nodes for Server Explorer.
> 
> Azure Data Lake Tools for Visual Studio 2.3.3000.2
> Microsoft Azure Data Lake Tools for Visual Studio
> 
> Azure Functions and Web Jobs Tools 15.8.05023.0
> Azure Functions and Web Jobs Tools
> 
> Azure Stream Analytics Tools for Visual Studio 2.3.3000.2
> Microsoft Azure Stream Analytics Tools for Visual Studio
> 
> C# Tools 2.9.0-beta8-63208-01
> C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.
> 
> Common Azure Tools 1.10
> Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.
> 
> GitHub.VisualStudio 2.5.6.4958
> A Visual Studio Extension that brings the GitHub Flow into Visual Studio.
> 
> JavaScript Language Service 2.0
> JavaScript Language Service
> 
> JetBrains ReSharper Ultimate 2018.2.3 Build 182.0.20180912.70621
> JetBrains ReSharper Ultimate package for Microsoft Visual Studio. For more information about ReSharper Ultimate, visit http://www.jetbrains.com/resharper. Copyright © 2018 JetBrains, Inc.
> 
> Microsoft Azure HDInsight Azure Node 2.3.3000.2
> HDInsight Node under Azure Node
> 
> Microsoft Azure Hive Query Language Service 2.3.3000.2
> Language service for Hive query
> 
> Microsoft Azure Stream Analytics Language Service 2.3.3000.2
> Language service for Azure Stream Analytics
> 
> Microsoft Azure Stream Analytics Node 1.0
> Azure Stream Analytics Node under Azure Node
> 
> Microsoft Azure Tools 2.9
> Microsoft Azure Tools for Microsoft Visual Studio 2017 - v2.9.10730.2
> 
> Microsoft Continuous Delivery Tools for Visual Studio 0.4
> Simplifying the configuration of Azure DevOps pipelines from within the Visual Studio IDE.
> 
> Microsoft JVM Debugger 1.0
> Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines
> 
> Microsoft Library Manager 1.0
> Install client-side libraries easily to any web project
> 
> Microsoft MI-Based Debugger 1.0
> Provides support for connecting Visual Studio to MI compatible debuggers
> 
> Microsoft Visual Studio Tools for Containers 1.1
> Develop, run, validate your ASP.NET Core applications in the target environment. F5 your application directly into a container with debugging, or CTRL + F5 to edit & refresh your app without having to rebuild the container.
> 
> NuGet Package Manager 4.6.0
> NuGet Package Manager in Visual Studio. For more information about NuGet, visit http://docs.nuget.org/.
> 
> Project 1.0
> Information about my package
> 
> ProjectServicesPackage Extension 1.0
> ProjectServicesPackage Visual Studio Extension Detailed Info
> 
> Redgate ReadyRoll 1.17.18155.10346
> Extend DevOps processes to your SQL Server databases and safely automate database deployments.
> 
> Visit https://www.red-gate.com/readyroll for more information.
> 
> Copyright (C) 2011 Red Gate Software Ltd. All rights reserved.
> 
> This software contains components from Component Owl.
> SQL Server is a registered trademark of Microsoft Corporation.
> Visual Studio is a registered trademark of Microsoft Corporation.
> 
> ReadyRoll contains code from the following open source software:
> 
> NuGet https://www.nuget.org/
> SQL LocalDB Wrapper https://github.com/martincostello/sqllocaldb
> Autofac https://autofac.org/
> Json.NET https://json.net/
> MahApps.Metro http://mahapps.com/
> SemVer https://github.com/maxhauser/semver
> Log4Net http://logging.apache.org/log4net/
> StringTemplate https://github.com/antlr/stringtemplate4
> Extended WPF Toolkit https://wpftoolkit.codeplex.com/
> Code InfoBox VSX http://www.codeproject.com/Articles/55196/Code-InfoBox-Visual-Studio-Extension-VSX
> OctoPack https://github.com/OctopusDeploy/OctoPack
> SQLite https://sqlite.org/
> 
> This product contains icons from http://www.visualpharm.com distributed under a free backlink license.
> 
> For license details or other notices relating to the above software, please see NOTICE.TXT and EULA.rtf in the ReadyRoll application folder.
> 
> Redgate SQL Prompt 9.3.0.6627
> Write, format, and refactor SQL effortlessly
> 
> ResourcePackage Extension 1.0
> ResourcePackage Visual Studio Extension Detailed Info
> 
> ResourcePackage Extension 1.0
> ResourcePackage Visual Studio Extension Detailed Info
> 
> Snapshot Debugging Extension 1.0
> Snapshot Debugging Visual Studio Extension Detailed Info
> 
> SQL Server Analysis Services 14.0.1016.285
> Microsoft SQL Server Analysis Services Designer
> Version 14.0.1016.285
> 
> SQL Server Data Tools 15.1.61808.07020
> Microsoft SQL Server Data Tools
> 
> SQL Server Integration Services
> Microsoft SQL Server Integration Services Designer
> Version 14.0.3002.113
> 
> SQL Server Reporting Services 14.0.1016.285
> Microsoft SQL Server Reporting Services Designers
> Version 14.0.1016.285
> 
> SsmsVsIntegration 1.0
> Information about my package
> 
> ToolWindowHostedEditor 1.0
> Hosting json editor into a tool window
> 
> TypeScript Tools 15.8.20822.2001
> TypeScript Tools for Microsoft Visual Studio
> 
> Visual Basic Tools 2.9.0-beta8-63208-01
> Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.
> 
> Visual F# Tools 10.2 for F# 4.5 15.8.0.0. Commit Hash: 55a3dc3231c95c77f81ee53f7d29152029da7408.
> Microsoft Visual F# Tools 10.2 for F# 4.5
> 
> Visual Studio Code Debug Adapter Host Package 1.0
> Interop layer for hosting Visual Studio Code debug adapters in Visual Studio
> ## Visual Studio Tools for Containers 1.0
> Visual Studio Tools for Containers
> 
> Since then, i am getting the error. I tried clearing the cache from %appdata% settings etc, but like [#1859 (comment)](https://github.com/github/VisualStudio/issues/1859#issuecomment-412916074) said, it pops up after i restart. The only thing i havent done is update my VS version to latest from 15.8.5 to 15.8.6 (as of today).
> 
> either i have to remove the Github extn or have to see how best i can go back to previous version or try update my VS and see if that may solve.
> 
> Can someone point me to the solution what was done or what needs to be done to solve this?

Well this revert helped. I just did that, reverting to previous version of the GitHub extension and NO RESTART of OS/Machine but just the VS, solved it. I opened 3 VS instances and solutions back to back, and nothing popped up so far! 

thanks to [this post](https://developercommunity.visualstudio.com/solutions/308088/view.html), it helped.

**Comment by iSamuel51** [comment]
Firstable, you need to be sure have the last Microsoft .NET Framework version, in my case, I had the 4.6 version and I have downloaded and updated the .NET Framework 4.8.03761 Developer Pack, from the official site:

https://dotnet.microsoft.com/download/dotnet-framework/net48

Once I restarted my PC, to continue fixing that, I solved this problem by clearing Visual Studio Component Model Cache.

Just delete or rename this folder:

%LocalAppData%\Microsoft\VisualStudio\11.0\ComponentModelCache
or

%LocalAppData%\Microsoft\VPDExpress\11.0\ComponentModelCache
and restart Visual Studio.
