### ISSUE TITLE
Development Sprint: October 1st Release

### ISSUE THREAD

**Issue by sguthals** [github/VisualStudio#1899]
Welcome to our first Development Sprint Issue tracking our release for October 1st!

# Overview
__Release Date:__ October 1st, 2018
__Description:__ This development sprint will be focused on cloning, annotations, internationalization, and improvements to our metrics and documentation. 
__Review Period:__ September 17th - 21st
_Expect to have all PRs for this release reviewed and merged by the end of the review period_
__Testing Period:__ September 24th - 28th
_Expect to have the Master branch tested and the release prepped by the end of the testing period_

# Goals
## Community Engagement Goal
_Are there PRs from community members?_

## Hypothesis Pre-Release
We will be seeking to validate/invalidate to these hypothesis prior to release.

| Hypothesis | Test | Status | Next Steps | Owner |
| ----------- | ---- | ------- | ----------- | ------ |

## Hypothesis Post-Release
We will be seeking to validate/invalidate to these hypothesis during the next development cycle.

| Hypothesis | Test | Status | Next Steps | Owner |
| ----------- | ---- | ------- | ----------- | ------ |

## Metrics Added
| Title | Link | Owner | Status |
| ---- | ----- | ------ | ------ |
| Show clone URL tab by default (A/B testing) | #1944 | @jcansdale | RfR |

## Tests Added or Improved
| Title | Link | Owner | Status |
| ---- | ----- | ------ | ------ |
|  Integration Tests | https://github.com/github/VisualStudio/pull/1884 | @jcansdale | WIP |
## Documentation Added or Improved
| Title | Link | Owner | Status |
| ---- | ----- | ------ | ------ |

## Bugs Resolved
| Title | Link | Owner | Status |
| ---- | ----- | ------ | ------ |

## PRs Merged
| Title | Link | Owner | Status |
| ---- | ----- | ------ | ------ |
| Refactor Clone Dialog | https://github.com/github/VisualStudio/pull/1787 | @grokys | Done |
| Check Run Annotations | https://github.com/github/VisualStudio/pull/1864 | @stanleygoldman | WIP |

**Comment by meaghanlewis** [comment]
One thing I've been thinking about in terms of this release tracker is that it's the high-level features in each release that will each have: hypotheses, metrics, tests, and documentation rather than all of those being separate things on their own.

Example:

# FEATURES / ENHANCEMENTS

**Feature: [Refactored Clone Dialog](https://github.com/github/VisualStudio/pull/1787)**
**Owner:** Steven
**Status:** 💚  (On-track)
**Hypothesis:** Users will have a greater experience using the clone dialog after is uses GraphQL to load the repository faster list and an added option to clone by URL. We expect to see the number of clones increase.


|      Artifact name           | Description | Link | 
| --------------- | ----------- | --------- |
| Tests | unit tests were added | https://github.com/github/VisualStudio/pull/1787 |
| Metrics | metric added to see how many users clone by URL: `NumberOfClonesByURL` | PR #  |
| Documentation | clone documentation updated | PR # |
| Usability studies | none for this feature | |

------------------------------------------------------

**Feature: [Check Run annotations](https://github.com/github/VisualStudio/pull/1864)**
**Owner:** Stanley
**Status:**  🏈 (punted for next release while we continue to iterate)
**Hypothesis:** Users will get more information about their build status inside of Visual Studio for each PR meaning they spend more time using our extension.

|      Artifact name           | Description | Link | 
| --------------- | ----------- | --------- |
| Tests | unit tests were added | https://github.com/github/VisualStudio/pull/1864 |
| Metrics | metric added to track when annotations are viewed | PR #  |
| Documentation | documentation in progress for this feature | PR # |
| Usability studies | 1 done on 9/20 | https://drive.google.com/drive/u/1/folders/14mdDrWHd-CC6CMkQeeBjeIq3Y1zaDcSF?ogsrc=32 |

# BUGS

## Bugs Resolved
| Title | Link | Owner | Status |
| ---- | ----- | ------ | ------ |
| Extension sometimes doesn't activate on GitHub repository | https://github.com/github/VisualStudio/issues/1924 | Jamie | ✅  |

**Comment by sguthals** [comment]
I LOVE this @meaghanlewis Thank you!
