### ISSUE TITLE
Unable to add reply to comments 

### ISSUE THREAD

**Issue by parvezapathan** [github/VisualStudio#2144]
![image](https://user-images.githubusercontent.com/6031087/50210251-a22c1180-0343-11e9-860f-6d48095bf155.png)

**Comment by jcansdale** [comment]
👋 @parvezapathan,

Thanks for the report. This is an annoying issue and I'm working on a fix!

The problem is that the diffing algorithm that the extension uses is slightly different to the one used on github.com. This can cause line number mismatches, hidden comments and situations where comments can't be submitted.

Here is a related issue and a WIP PR:
- #1469 Inline comment appears on PR page but not in GitHub extension
- #2142 Update to use modern version of LibGit2Sharp and use indent heuristic when diffing

**Comment by itsrehanijaz** [comment]
test
