### ISSUE TITLE
Account not hightlight in commits

### ISSUE THREAD

**Issue by cuongw** [github/VisualStudio#2150]
Hi guys,
I have been this issue althought i added all mails that i am using for my account in Github Settings.
I am using Window 10 and local account. Local account is reason??? Other commit with other mail is ok.
Thanks !🙏 
![imageedit_2_7387910671](https://user-images.githubusercontent.com/34389409/50395340-e8470200-0795-11e9-9add-1c6ef47dfc9f.gif)

**Comment by meaghanlewis** [comment]
Hi @jade28 sorry but I'm not sure exactly what the problem is you're describing here. Are the commits you highlighting coming from an account you don't expect? Does this problem continue to happen now?

**Comment by meaghanlewis** [comment]
👋 @jade28, sorry for the late response. Are your newer commits are coming from the right account and being highlighted as you expect? 

If you are still experiencing problems with these old commits and curious about why this is happening it would be best to report the issue here: https://github.com/contact so your request can be routed to our accounts team.
