### ISSUE TITLE
Only show `Sign in with your browser` option in sign in dialog

### ISSUE THREAD

**Issue by meaghanlewis** [github/VisualStudio#2194]
### Summary

We have had lots of conversations about our sign-in workflow over the last couple months.

One thing we have discussed is only showing the option to `Sign in with your browser` and removing additional fields. This will simplify sign in for users and save them time. 

- For signing in with `GitHub` this means removing the username or email and password field.
- For signing in with `GitHub Enterprise` this means keeping the server address field and removing the token field.

Example:
![sign in with your browser](https://user-images.githubusercontent.com/10103121/51572853-d079a100-1e5b-11e9-8544-be83426f5f5d.png)

Perhaps we could make the dialog look similar to the SSO to GitHub dialog:
<img width="300" alt="screen shot 2019-01-23 at 7 38 27 am" src="https://user-images.githubusercontent.com/10103121/51617911-0b261c80-1ee2-11e9-90da-e8d3887927d0.png">

**Comment by meaghanlewis** [comment]
What thoughts do you have about this @donokuda @grokys @jcansdale @StanleyGoldman? And @donokuda any ideas on what the dialog could look like?

**Comment by donokuda** [comment]
I made a [prototype](https://www.figma.com/proto/dPA1JODCJZlPz1zL2XLpVPwP/Visual-Studio-Sign-in-Next?node-id=28%3A4&viewport=285%2C269%2C1&scaling=min-zoom) in Figma to walk through a sign-in with the login fields deemphasized.

Here's a gif walkthrough regardless:

<img src="https://user-images.githubusercontent.com/1174461/52238402-bc349b80-2880-11e9-9b65-db9d082d9099.gif" width="428" />

I tried to incorporate @grokys's [suggestion](https://github.com/github/VisualStudio/pull/2201#issuecomment-458946143):  

> What about: when opening the dialog, show a button saying "Sign in with your browser", and below it a smaller link saying "Sign in with username and password" and only when you click that button the UI changes to display the user/pass boxes? 


I also modified the Enterprise login flow slightly where we show a disabled Sign In button and then show/hide any UI's as needed:

![image](https://user-images.githubusercontent.com/1174461/52242289-218d8a00-288b-11e9-91a9-f4a592cab9aa.png)

Currently in @jcansdale's [pull request](https://github.com/github/VisualStudio/pull/2201), the Enterprise tab shows only a field until you type in a valid enterprise instance URL:

![image](https://user-images.githubusercontent.com/1174461/52241311-2866cd80-2888-11e9-9342-d911a72801ee.png)

However, the form looked strange and incomplete to me because a submit button doesn't appear until you fill in the single field. By adding a submit button, the form doesn't feel as much as a "dead end"

I [pushed a branch](https://github.com/github/VisualStudio/tree/donokuda/sign-in-ui-test) that tests laying out the initial sign in screen, but I got blocked trying to stub out the other parts of my proposal.

**Comment by jcansdale** [comment]
This has been done. I hope you're well @meaghanlewis! 😄
