### ISSUE TITLE
Add a "Private Repository" default value setting

### ISSUE THREAD

**Issue by tom0dea** [github/VisualStudio#2244]
Is it possible to add a global setting so the user can set "Private Repository" as the default option when creating new repositories?

![2019-02-26 18_42_04-start page - microsoft visual studio](https://user-images.githubusercontent.com/626463/53454768-44c4d880-39f6-11e9-86ad-07b7c89457d8.png)

**Comment by jcansdale** [comment]
We've tended to avoid options because their discoverability is poor and they add to the matrix of things we need to test. It's easy to end up with rarely used and poorly tested functionality. Unless this option is added to github.com, I'd be reluctant to add it to the extension.

I hope that make sense. Thanks for the suggestion.

**Comment by jcansdale** [comment]
We might support this if github.com adds a setting to change the default.
