### ISSUE TITLE
Translation: GitHub tools for Visual Studio has inaccurate zh-cn translations

### ISSUE THREAD

**Issue by alpaix** [github/VisualStudio#2289]
[Moved from Developer Community. Ticket 801290]

The "Pluse" has been translated into "脉冲". This is inaccurate. "脉冲" has the meaning of pulse as in "pulse of current", "pulse of radiation", rather than "news, updates, development cadence". Perhaps "动态" might be a better one.

The translation of "Fork" is missing.

There are other translations that I may have some suggestion: I think "tag" can be translated as "标签" (something more like "label") instead of "标记".

**Comment by meaghanlewis** [comment]
👋 @alpaix thanks for opening up this issue. 

Just to add some more context, we worked with the Globalization team at Microsoft, and they provided all the translations that we use. Since then a few users have brought up issues with some translations, specifically for the Chinese language.

Are you the one who opened the original issue that you referenced? If so, and if you speak Chinese then we would love your feedback on any other translations you find to not be accurate so we can pass them all on to the translation vendor and see how we can reconcile the differences.

**Comment by alpaix** [comment]
@meaghanlewis I do not speak Chinese. This issue was reported by a customer via "Report-a-Problem" tool in Visual Studio. Our general guidance is to re-route feedback tickets related to GitHub VS extension to this repository. Here is the original report:
https://developercommunity.visualstudio.com/content/problem/467336/translation-github-tools-for-visual-studio-has-ina.html

**Comment by meaghanlewis** [comment]
Alright, thanks for your response @alpaix!

**Comment by johnliu2016** [comment]
On linguistic review

**Comment by lukaschal** [comment]
Fixed.

ENU: Pulse
CHT: 動態

ENU: Fork
CHT: 分支
