### ISSUE TITLE
Solution Explorer -> Right click file -> commit : not staging the file for commit.

### ISSUE THREAD

**Issue by rasmuseeg** [github/VisualStudio#236]
![image](https://cloud.githubusercontent.com/assets/1511208/13635171/6f2faa4e-e5fa-11e5-94bd-0bd15840f584.png)

Clicking the commit action doesn't stage selected files.

**Comment by Haacked** [comment]
Hi @rasmuseeg, the commit functionality is part of the built-in Git support for Visual Studio. This repository is for the GitHub Extension for Visual Studio. I know it's confusing because a lot of people equate Git and GitHub. :wink:

You can log a [bug for Visual Studio in their Connect site](https://connect.microsoft.com/VisualStudio/feedback/LoadSubmitFeedbackForm). For feature requests, the Visual Studio team [has a UserVoice](https://visualstudio.uservoice.com/forums/121579-visual-studio-2015). Good luck!
