### ISSUE TITLE
Disable popup of Open solution dialog when selecting repository

### ISSUE THREAD

**Issue by xperiandri** [github/VisualStudio#239]
I don't want to select repository from Open solution dialog box when I select a repository.
I usually open it from repository home page in Team Explorer.
Could you add an option to disable current behavior?

**Comment by shana** [comment]
You mean the Open Solution dialog that shows up when you double click on a repo in the Connect page?

Showing the dialog is the only way of switching repository contexts because VisualStudio doesn't provide an API to set the current repository. If you close the dialog, it won't do anything. If you want to select a repository without opening a project, select it from the Local Repositories list.

**Comment by shana** [comment]
@clboles We could really use an API to switch repositories, the current usability is poor :/

**Comment by xperiandri** [comment]
But it worked earlier.
And if I close dialog it switches repositories

**Comment by shana** [comment]
@xperiandri It really doesn't, I'm afraid. In the Connect page, if you double click on a repository in the GitHub list of repositories, the only thing it does is show a Open Solution dialog. If you close the dialog without opening a solution, it won't switch repositories. The only way of switching repositories that we have is by opening a solution or project.
