### ISSUE TITLE
GitHub repository not listed

### ISSUE THREAD

**Issue by SoftCircuits** [github/VisualStudio#2392]
I have several local repositories that are also mirrored in GitHub repositories. This has worked well and I've been able to push my changes to GitHub successfully.

But now one of my repository is no longer showing up in the list of GitHub repositories. If I try to publish the local repository, I get an error saying the repository already exists.

In the image below, you can see the local Git repositories includes one repository called Toxic. But that repository does not show up in the GitHub list at the top. And I can find no way to add it.

![Untitled](https://user-images.githubusercontent.com/3191331/60119078-dccf9600-973a-11e9-9e2e-170b04fec125.png)

**Comment by jcansdale** [comment]
Sorry about the late reply!

Does your Toxic repository have a remote named `origin`? GitHub for Visual Studio special cases remotes named `origin` in order to find the home of a repository. If no `origin` remote exists, it won't know that it's already published on github.com.

I wonder if that is the problem you're seeing?
