### ISSUE TITLE
GitHub Extension for Visual Studio won't install on VS Code - extension/package.json not found inside zip.

### ISSUE THREAD

**Issue by jharris1993** [github/VisualStudio#2434]
## Versions
 - GitHub Extension for Visual Studio version:  2.10.7.8114

 - Visual Studio Code version:  1.39.2

## What happened
Attempting to install the GitHub extension into Visual Studio Code fails with a "extension/package.json not found inside zip." error.

Notes about this issue:
1.  Double-clicking the package does not install it as .vsix files are apparently not registered as VS Code files by Visual Studio Code.
2.  Attempting to install the .vsix file directly from the extensions manager returns the extension/package.json not found inside zip. error

### Steps To Reproduce
Steps to reproduce: (from within VS Code)
(This assumes you have downloaded the extension and have saved it somewhere on your local machine)
1. Open VS Code
2.  Navigate to the extensions manager (a cube of blocks icon on the far left)
3.  Select the three dots, (. . .) in the upper right corner of the extension manager's window
4.  Select "Install from VSIX file" near the bottom of the drop-down menu
5.  Browse to the .vsix file you downloaded and select install.
6.  The "extension/package.json not found inside zip." error is raised in the lower right hand corner of the VS Code window.

### Expected behavior
1.  The extension should install.
-- or --
2.  Something should indicate that this extension is *NOT* compatible with Visual Studio Code.

### Additional Commentary
There doesn't seem to be any indication that the GitHub Extension for Visual Studio extension is incompatible with VS Code.  If this true, perhaps this should be made clear both on GitHub and on the download site for the extension.

Thanks!

**Comment by sdholden** [comment]
Seeing same issue on VSCode 1.40.2 on Ubuntu.  Will try on W10 and see if it happens there as well

**Comment by abou7abiba** [comment]
I tried it on Version: 1.41.1 on windows 10 (OS: Windows_NT x64 10.0.18362) and I had the same problem.

**Comment by jimmy-mai** [comment]
Also on 1.41.1 on Windows 10 with the same issue.

**Comment by mavaddat** [comment]
This extension is built for [Microsoft Visual Studio](https://visualstudio.microsoft.com/), which is the full IDE by Microsoft. [Visual Studio Code](https://github.com/microsoft/vscode) is an open source text-editor also made by Microsoft. Extensions built for [Visual Studio](https://visualstudio.microsoft.com/) will not work for [Visual Studio Code](https://github.com/microsoft/vscode) or vice versa.
It is easy to confuse these two, since Microsoft used the same logo (different colours) and nearly the same names for each application.
Please see [this StackOverflow query](https://stackoverflow.com/questions/30527522/what-are-the-differences-between-visual-studio-code-and-visual-studio) for more information.

**Comment by jcansdale** [comment]
Thanks for letting them know @mavaddat! 👍
