### ISSUE TITLE
Github Owner is not set when Creating a Git repository after update to Visual Studio 2019 16.7.0 preview 3

### ISSUE THREAD

**Issue by TomaszGrzmilas** [github/VisualStudio#2525]
![github](https://user-images.githubusercontent.com/32311696/85523517-5d9fc700-b607-11ea-9347-9107f1086875.png)

Everything was working before update, settings did not change.

One more thing, the buttons are smaller. I don't know if this is intended.

![github2](https://user-images.githubusercontent.com/32311696/85523621-858f2a80-b607-11ea-966f-5a2ffd96301f.png)

**Comment by jcansdale** [comment]
Hi @TomaszGrzmilas,

I think https://github.com/github/VisualStudio/issues/2523 might be the same issue? See the comment at the bottom (this functionality is now part of VS).

> One more thing, the buttons are smaller. I don't know if this is intended.

@daschult what do you think about this ☝️ ?

**Comment by TomaszGrzmilas** [comment]
Hi @jcansdale ,

> 
> I think #2523 might be the same issue? See the comment at the bottom (this functionality is now part of VS).
>

I don't have any problem, when the repository was initialized before updating to 16.7.0 preview 3.
Error is when I want to initialize a repo after today update to last preview version.

I'm not using extension, I'm using build in github support.

![github](https://user-images.githubusercontent.com/32311696/85538943-a52d4f80-b615-11ea-82a0-944b844e24c4.png)

> 
> > One more thing, the buttons are smaller. I don't know if this is intended.
> 
> @daschult what do you think about this ☝️ ?

It's looking nice for me :)

**Comment by daschult** [comment]
Yes the buttons are smaller. This was a recent decision because people felt that it looked nicer. Everyone is entitled to their own opinions. I preferred the larger buttons, but oh well. 🤷 

With regards to the owner problem, that was definitely a bug in the VS Version Control code base (not really related to this repository). We've fixed the problem and the fix should be coming out either in the next preview version of Visual Studio or the one after that (depending on when you read this comment).

Sorry about the trouble it's caused, but we'll got it taken care of now. 😄

**Comment by TomaszGrzmilas** [comment]
@daschult  
Ok ! 

Thank you for info. Waiting next release.

VS team are making very good work. Thx 4 that !

**Comment by WALLOUD** [comment]
****
