### ISSUE TITLE
Issue for Changes page in VS2015 Update2

### ISSUE THREAD

**Issue by Myfreedom614** [github/VisualStudio#253]
After upgrading to **update 2** yesterday, the Github Changes page has broken:

- **Screenshot for VS2015 Update1:**
![vs2015update1](https://cloud.githubusercontent.com/assets/2476467/14196348/0d224678-f7f6-11e5-999a-5059f71ecf7f.jpg)

- **Screenshot for VS2015 Update2:**
![vs2015update2](https://cloud.githubusercontent.com/assets/2476467/14196347/0d223c64-f7f6-11e5-80d3-5e566c81a6bc.jpg)

No Included Changes/Excluded Changes.......

**Comment by shiftkey** [comment]
This is the local Git for Visual Studio integration, which is separate to the extension.

And I believe this change is by design, as you now select "Stage" from the context menu - which IMO feels more natural to Git than included/excluded:

<img width="495" src="https://cloud.githubusercontent.com/assets/359239/14246362/abe61ae2-fa34-11e5-8602-39f9c2f2d9b2.png">

This then indicates which items are staged, ready for commit:

<img width="335" src="https://cloud.githubusercontent.com/assets/359239/14246387/c94a77cc-fa34-11e5-9c74-8737a93ca0f2.png">

Anyway, if you're not happy with this change to the Git integration please submit feedback to the team using the in-app tool (available from the person icon in the top-right):

<img width="280" alt="screen shot 2016-04-04 at 7 15 15 am" src="https://cloud.githubusercontent.com/assets/359239/14246443/1454871c-fa35-11e5-8847-20880ccf4151.png">
