### ISSUE TITLE
QA for Release 1.0.18.3/1.0.18.4

### ISSUE THREAD

**Issue by mponce1** [github/VisualStudio#310]
Results from manifest: https://github.ontestpad.com/script/99#/1/
Issues found as part of manifest: 
Issues found through new features / enhancements: https://github.com/github/VisualStudio/issues/307 https://github.com/github/VisualStudio/issues/309

**Comment by shana** [comment]
This is awesome, thank you!

**Comment by mponce1** [comment]
All open issues closed. 👍

**Comment by shana** [comment]
Le thank you!

**Comment by shana** [comment]
Looks like a couple of fixed issues were missing from the release notes:

#276 - Entries in the Clone dialog repository list can be collapsed per user/org
#242 - Validation Adornment persists after error is corrected

In the case of #276, might require changes to the manifest, since it's a behaviour change.

**Comment by mponce1** [comment]
Verified all fixed.

**Comment by shana** [comment]
Yay, thanks! ^_^
