### ISSUE TITLE
GitHub pane appears blank when current repository is not a GitHub repo.

### ISSUE THREAD

**Issue by grokys** [github/VisualStudio#356]
There are 3 situations we need to handle here:

1. There is no project loaded and the Team Explorer has source control context
2. There is a project loaded but it's not a git repository
3. There is a project loaded but it's not a GitHub repository

**Comment by shana** [comment]
Ayup.

**Comment by grokys** [comment]
@donokuda any idea what this should look like?

**Comment by donokuda** [comment]
We could go with the same approach as the [logged out view](https://github.com/github/VisualStudio/pull/266) in terms of layout.

I think we should use this as an opportunity to publish their repository to GitHub so they can start using what our extension offers immediately such as creating a pull request.

Here are some mocks to illustrate what I was thinking:

<img width="628" alt="screen shot 2016-06-15 at 10 25 12 am" src="https://cloud.githubusercontent.com/assets/1174461/16090234/78df430c-32e3-11e6-99cc-f85849c4c735.png">

Here's an alternative version using the primary button styles because yey options!

<img width="620" alt="screen shot 2016-06-15 at 10 22 25 am" src="https://cloud.githubusercontent.com/assets/1174461/16090127/14753f3e-32e3-11e6-9e9e-7e6f20ddf5c2.png">

That said, I'm curious if there's a way where we can ship this message without publishing as a first pass (because having something explaining why the pane is empty is better than nothing.) We could link to the "Create Repo" page, but I'm not sure how to bring the flow back to Visual Studio without making it feel "disconnected."

**Comment by donokuda** [comment]
PS. If there's a view already set up for this, I can stub something out for you 😄

**Comment by grokys** [comment]
Looks good to me! There's no view currently set up - will do that now.

**Comment by grokys** [comment]
@donokuda ok, there's a blank view on the `fixes/356-not-a-github-repository` branch at:

https://github.com/github/VisualStudio/blob/fixes/356-not-a-github-repository/src/GitHub.VisualStudio/UI/Views/NotAGitHubRepositoryView.xaml

Work your magic! :space_invader:

**Comment by donokuda** [comment]
✨ 🎩 ✨ 

I added some content in 64ef6c6ab95fe2c3fa0d3b8fc45959eaf23f9712.

❓ Is the publish button the only thing needed for this flow? After looking at our create a repo modal, I think we'll want to ask for a name, description, and which account to add the repo to:

![image](https://cloud.githubusercontent.com/assets/1174461/16128792/e5e18798-33b6-11e6-9ff5-2e426c3fb7a9.png)

Is there something that exists for publishing an existing repo to GitHub in our extension? If so, it would be interesting to see if the publish button takes the user to that. If not, then that's something we should design.

Regardless, here's how it currently looks like! 

![mmm-no-repo](https://cloud.githubusercontent.com/assets/1174461/16128439/9a89db02-33b5-11e6-9748-d4cf4aa37a2e.png)

**Comment by shana** [comment]
We already have a publish to github view in the Team Explorer area:

![screen shot 2016-06-17 at 12 44 18 pm](https://cloud.githubusercontent.com/assets/310137/16148339/4dc9438c-3489-11e6-91b3-812e7ea6aa26.png)

![screen shot 2016-06-17 at 12 46 54 pm](https://cloud.githubusercontent.com/assets/310137/16148398/a457c610-3489-11e6-98b6-ae934f5f3b53.png)

![screen shot 2016-06-17 at 12 47 11 pm](https://cloud.githubusercontent.com/assets/310137/16148402/aaa38a9a-3489-11e6-9eba-d0d9216b202d.png)

We can embed that in our pane or jump to it.

On a different note, I've been doing the PR creation and I'm finding the green button pretty hard to read. The white on flat green just disappears. It's also almost impossible to tell when it's enabled/disabled, too :/

**Comment by donokuda** [comment]
> On a different note, I've been doing the PR creation and I'm finding the green button pretty hard to read. The white on flat green just disappears. It's also almost impossible to tell when it's enabled/disabled, too :/

Looked into this and it appears I have specified the wrong green hex for some reason... `facepalmpicard.jpg`

I'll open up a PR to fix this!

**Comment by grokys** [comment]
This was fixed by #374 - are we OK to close it?

**Comment by shana** [comment]
@grokys Yup, it's still open because the PR that fixed it doesn't have the issue number in the PR description so when it got merged this one didn't get closed.
