### ISSUE TITLE
Comment count in for PRs in list view missing

### ISSUE THREAD

**Issue by paladique** [github/VisualStudio#402]
![2016-07-05 3](https://cloud.githubusercontent.com/assets/1414307/16599972/eb1e5698-42d2-11e6-9670-44c9534c616e.png)

Currently all PRs in the list have a count of 0. The screenshot above shows a PR in the list that has comments on it on the repo/site, but not reflected in this list.

**Comment by StanleyGoldman** [comment]
I debugged this for a bit. The api call 'list-pull-requests' does not provide a comment count.
A CountToVisibilityConverter was added to the control so it no longer shows 0 at least.
![Image](http://i.imgur.com/saHtRUz.png)

**Comment by paladique** [comment]
Looks like this issue might be related to the discussion here: https://github.com/octokit/octokit.net/issues/1403

Thought this part was interesting:
>In my case I ended up using the Search Issue API to get a list of PRs for a specific repo that were merged in a specific date range, THEN i fired off concurrent async calls to load those subset of PR's individually. This still turned out to be much faster than loading all PRs for the repo with the single PullRequest.GetAllForRepository() call (as under the covers, that pages through multiple results). Also the GetAll call will get slower as the repository grows, whereas the search + parallel PR load is a bit more constrained

**Comment by shana** [comment]
Oh that's very interesting. Once we have a list of PRs loaded, we should be able to request only the ones that have changed since we last loaded the list, via the `If-Modified-Since [date]` header. We still need to do individual calls to get each PR so we can get these fields though - that means doing separate requests for the PRs that are currently displayed, probably, so we don't have a million calls going out every time.

**Comment by meaghanlewis** [comment]
Comment counts are no longer showing as `0`. Closing this out.

There is a somewhat related issue: https://github.com/github/VisualStudio/issues/1153, where the comment count doesn't update after deleting comments.
