### ISSUE TITLE
Source branch dropdown empty in Create PR window

### ISSUE THREAD

**Issue by grokys** [github/VisualStudio#404]
When I open the "Create PR" window the source branch dropdown is initially empty - this should be initialized with the current branch.

![image](https://cloud.githubusercontent.com/assets/1775141/16612925/c8d11214-4369-11e6-9760-1994ee132501.png)

**Comment by grokys** [comment]
In fact the current branch is not available in the dropdown:

![image](https://cloud.githubusercontent.com/assets/1775141/16613000/277bec80-436a-11e6-979b-cf0ec1533861.png)

Is this because I haven't pushed the branch? If so there should at least be a message to that effect.

**Comment by donokuda** [comment]
@grokys Most likely an oversight on my part, but the target branch (`master` in the case of the screenshot) should be the dropdown and not the current branch.

I think the dropdown not showing your current branch is correct because you can't open a PR to the same branch you're on. The current branch should be read only.

**Comment by grokys** [comment]
Ok, closing this because there is only one dropdown now.
