### ISSUE TITLE
Visual Studio crashes at Changes in Team Explorer in git-extention

### ISSUE THREAD

**Issue by gioragutt** [github/VisualStudio#46]
A couple of times, when I double right-clicked on a file in the to-be-committed list (haven't checked other items), it crashed visual studio. I tried clicking Debug once, and If I recall correctly It threw an InvalidCastException or something of that sort. I have yet succeeded in recreating the crash again so I cannot tell for sure if it is the right exception or not. I'll make sure to verify or update if the crash happens again.

**Comment by shana** [comment]
@gioragutt The git areas (commits, file lists, etc) are supported by MS, so that crash is more likely on their side than ours. You can send feedback to MS about the crash via the crash reporter or via the smiley icon in VS. In any case, if you can get it, post a stacktrace here (or more detailed info about the exception).
