### ISSUE TITLE
PR Creation: Branch error message doesn't clear when switching branches

### ISSUE THREAD

**Issue by shana** [github/VisualStudio#478]
If the "source is equal to target branch" error message is visible and the user switches branches, the message should be cleared.

**Comment by grokys** [comment]
To do this I think we'll need to uppdate the `INotificationsService` with the concept of "this error was cleared".

**Comment by shana** [comment]
That makes sense, maybe a `ClearErrors` or just a `Clear`?

**Comment by grokys** [comment]
Not sure - I think it would mean that `INotificationsService` would have to be stateful. Because the errors in the Create PR view aren't really "notifications" - they're errors that can't actually be dismissed - maybe it would make sense not to use that mechanism there and instead simply have an "ErrorMessage" property on the ViewModel?

**Comment by grokys** [comment]
Let me clarify what I mean by "Can't be dismissed": even if you close the error, the error state still persists, meaning that you still can't continue. Does it make sense to allow dismissal of the messages in that case?

**Comment by shana** [comment]
I can see it working both ways, but yeah, maybe having an Error property would be better in this case.

**Comment by meaghanlewis** [comment]
I can no longer get this message to appear at all.

![screen shot 2018-09-11 at 3 34 26 pm](https://user-images.githubusercontent.com/10103121/45391560-492c3f00-b5d8-11e8-88f9-9eae6cb90f21.png)

Going to close this out now.

**Comment by MarcinBlaszczukChelm** [comment]
[]() ``
