### ISSUE TITLE
Show a message when there are no pull requests for the current filter.

### ISSUE THREAD

**Issue by Haacked** [github/VisualStudio#499]
When I navigated to the PR pane, I saw this.

<img src="https://cloud.githubusercontent.com/assets/19977/17571120/c0f28d38-5f03-11e6-8af1-49120a9dc1a3.PNG" width="420" />

I thought maybe something was broken, but then I navigated to the PR list on GitHub.com.

![githubdotcom-no-prs](https://cloud.githubusercontent.com/assets/19977/17571103/b7b7c2ba-5f03-11e6-8c4f-b4b435189984.PNG)

We really do have no active PRs. Perhaps we should show a message similar to the one we show on the website. cc @donokuda

**Comment by donokuda** [comment]
We could use an empty blankslate similar to [what we do when you're not logged into GitHub](https://github.com/github/VisualStudio/pull/266).

![image](https://cloud.githubusercontent.com/assets/1174461/17707058/70f72296-6393-11e6-9486-c00fdf05569a.png)

I pulled the content from the [help article about Pull Requests](https://help.github.com/articles/using-pull-requests/) and added a link to it in case a user isn't familiar with what pull requests are. We can also consider linking to the "Create new" view instead of linking to the help article.

If this looks good, I can get this going if there's a view stubbed out or if someone could point me in the direction on how to create it 😄

**Comment by Haacked** [comment]
@donokuda :+1: looks good to me!

**Comment by meaghanlewis** [comment]
@grokys added this enhancement  🎉 
![no-open-prs](https://user-images.githubusercontent.com/10103121/42787598-027294dc-8910-11e8-9afa-2bbbd0a5d4cd.png)
