### ISSUE TITLE
The updated version on 8/13 totally does not work.

### ISSUE THREAD

**Issue by lovesha** [github/VisualStudio#51]
![githuberror](https://cloud.githubusercontent.com/assets/12118206/9266652/b4388746-4276-11e5-88a8-d54e7c9f0f62.jpg)

**Comment by shana** [comment]
@lovesha I'm sorry you're having this issue. It actually looks like the only thing that loaded was the GitHub parts. Everything else there is a part of the VS Team Explorer extension shipped by Microsoft, which is failing to load. It could be our extension messing up, however: could you uninstall the GitHub extension and see if it fixes it? Does it break again when you install it?

**Comment by lovesha** [comment]
Yes, I tried to uninstall and install again. The issue is still there. Do you know where I can download a previous version? So I can try if it works after rolled back.

**Comment by shana** [comment]
@lovesha Does Team Explorer work correctly if you uninstall the GitHub extension?

**Comment by shana** [comment]
@lovesha Just to clarify: those error messages that you see are coming from the Team Explorer extension that is shipped by Microsoft in Visual Studio. The area that says "GitHub" and "Clone | Create | Sign out" is the only part in that screen that is actually handled by the GitHub extension, and it looks like it's working correctly. This means that this problem likely didn't happen because of the GitHub extension, but it is instead a problem with Visual Studio itself.

I can arrange for a previous version of the GitHub extension to be available for download, but first I'd like to verify if your installation of VS is having problems or not. Let me know if these errors persist when you uninstall the GitHub extension.

/cc @clboles @mtbandolier

**Comment by lovesha** [comment]
@shana Thanks for your information. The problem happened when I upgraded two extensions. One is github, the other one is nuget. The team explorer didn't changed and it is working fine now with TFS. 

The wired thing is when I try it again today. The issue is gone.... I cannot repro it.

**Comment by shana** [comment]
@lovesha Sometimes the VS extension cache gets messed up, and since Team Explorer is an extension, it might get affected. In cases like this, one good thing you can do to try and repair VS is to close VS, open a visual studio command prompt and run `devenv /updateConfiguration`. This will fix any stale cache or extension misconfigurations you might have. After it's done, you can run VS normally and things should be fixed.
