### ISSUE TITLE
UIProvider.GitServiceProvider

### ISSUE THREAD

**Issue by grokys** [github/VisualStudio#540]
`UIProvider` contains a `GitServiceProvider`, however:

- As in #539 it masks where a service is actually coming from
- And worse, the `GitServiceProvider` is set via a public setter from what seems to be a completely unrelated operation, i.e. when `GitHubConnectSection.StartFlow` is called. This introduces a confusing coupling between UI flow and service provider behavior, which I imagine could easily be a source of bugs.

I understand things are probably this way due to the vagaries of VS, but I wonder if there's a better way to do it? I suspect it's things like this that cause our occasional loading order bugs.

**Comment by shana** [comment]
The `IServiceProvider` that provides the git service is only available in Team Explorer class instances. When any class that implements an `ITeamExplorerXXX` interface is instantiated, the service provider it receives during the Initialize call has the ability to provide it the git service provider we need to do cloning and other things.

`IUIProvider` acts as a centralized wrapper for accessing every service we need, and it's a singleton, so whenever we get a service provider that can give us the git service, it's stored in that property for everyone else to access (the git service provider is sort of ephemeral, and I haven't quite figured out what the lifetime of the actual service is). This was before I added the mechanism to manually register services in the `IUIProvider`, of course. Now that that exists, `GitServiceProvider` can probably be killed in favor of registering something in `AddService` and using it for the lookups.

As for loading order: Team Explorer loads the git service and the information on the active repository in a background thread. There is no guarantee of when things are actually available, which is why our UI thinks there's nothing there sometimes.

**Comment by grokys** [comment]
Ok, that's kinda what i suspected, however something is maybe still wrong?

- Put a breakpoint on the `UIProvider.GitServiceProvider` setter
- Run VS and it doesn't get called
- Open the team explorer "Connect" page and it gets called

So it's not getting loaded until the "Connect" page is opened.

However note that the `UIProvider.GetServiceProvider` is set using the value of `TeamExplorerBase.ServiceProvider`. If you put a breakpoint on *that* setter, you will see it gets set when Team Explorer opens, i.e. it looks like this service is available earlier than we're making it available. Or is that value no good as a `GitServiceProvider`?

What's confusing is that when the connect page opens, *another* service provider is passed in. Why are they different instances? Which one should we use? What are you doing VS?

**Comment by shana** [comment]
We do not set it when the TE home page is visible because nothing in there requires the git service and getting an instance of `IUIProvider` there to set things would cause all dependencies to load and MS to shout at us. `TeamExplorerBase.ServiceProvider` gets set every time any subclass gets instantiated, based on the value passed to the instance in the `Initialize` call. The service provider instances that are passed into initialize (and stored in `TeamExplorerBase.ServiceProvider`) run out of "scope" when the UI goes away, they're only valid for the lifetime of the UI (as far as I could figure out from when I was building this early last year).

The `IGitExt` service itself exists only when the repo is a git repo, and is only provided by these service providers. It is only put in the `GitProvider` property in the connect section because the only code that uses that service is the `RepositoryCloneService`, which does not have any access to the "magical" service provider that TE gives us to access the service.

**Comment by grokys** [comment]
Ok, that makes sense now I think, thanks :+1:
