### ISSUE TITLE
GitHubPackageTests doesn't have [Fact] attribute

### ISSUE THREAD

**Issue by grokys** [github/VisualStudio#541]
The [AddsTopLevelMenuItems](https://github.com/github/VisualStudio/blob/62567638cf02ea43885233147659f5b76665ddb6/src/UnitTests/GitHubPackageTests.cs#L11) test doesn't have a `[Fact]` attribute so isn't recognised as a test.

**Comment by shana** [comment]
I didn't even remember we had package tests :P

**Comment by paladique** [comment]
Added the `Fact` attribute back in, and this test was failing, after adding some additional mocks to get the test to the point of assertion, it failed because there are no menu items in the mocked menu service. Adding them as mocks seems like it would defeat the purpose of this test. With this, plus the upcoming changes in #528 should we keep this test?

**Comment by paladique** [comment]
Per discussion with @shana, delete the file containing the test.
