### ISSUE TITLE
Inconsistent UI for open PR branch

### ISSUE THREAD

**Issue by tocsoft** [github/VisualStudio#641]
- GitHub Extension version:  v2.0.15.3-alpha1
- Visual Studio version: 2015 Update 3

The _'local branch is missing'_ UI is inconsistent between when a pull request is from a fork or from the same origin.

**Local/remote branch**
![image](https://cloud.githubusercontent.com/assets/166440/19695760/4e4f2c4a-9adc-11e6-8fe9-3df9937f2894.png)

**Fork**
![image](https://cloud.githubusercontent.com/assets/166440/19695754/47ef657c-9adc-11e6-8374-9d5309d6b790.png)

I would expect the UI to look them same, not having the same actual contents each would be worded appropriately to the case, but either both to be buttons or both be warning messages with a link to download the pull request. 

My preference would be the warning text with a link.

**Comment by grokys** [comment]
Yeah, this is because when the PR comes from the same repository, *the branch already exists in the repository* which is the same state as after you've created a local branch for a PR from a fork.

You're right though that we might not want to use such a different visual appearance for the two states. Any thoughts @donokuda @saraford ?

**Comment by donokuda** [comment]
> You're right though that we might not want to use such a different visual appearance for the two states. Any thoughts @donokuda @saraford ?

👍 on treating the two scenarios as the same (by showing the `Checkout pull request` button.)
