### ISSUE TITLE
Publish to Repo from VS error when .gitignore exists

### ISSUE THREAD

**Issue by thecarlo** [github/VisualStudio#66]
Sequence of events :

1) Create a repo (public or private) on GitHub and add visualstudio .gitignore
2) Create local repository, commit to that
3) Sync to repo on GitHub and you get an error. 

For this to work you have to create the repo on GitHub wihout .gitignore

**Comment by Haacked** [comment]
> Create a repo (public or private) on GitHub and add visualstudio .gitignore

By that, you mean check the ignore at the time that you create the repository?

> Create local repository, commit to that

How are you doing this? How did you connect this local repository to the one you created on GitHub.com?

> Sync to repo on GitHub and you get an error.

Could you describe the error or show a screenshot?

**Comment by thecarlo** [comment]
Correct, so create a repo on GitHub and att the .gitignore when creating the repo

Here's the full sequence of events :

![vs-github-error](https://cloud.githubusercontent.com/assets/5310264/9598957/289be9da-5090-11e5-8d67-40244cde5a43.jpg)

![vsgithuberror2](https://cloud.githubusercontent.com/assets/5310264/9598960/2e6824fa-5090-11e5-87da-02c0953dd8c1.jpg)

![vsgithuberror3](https://cloud.githubusercontent.com/assets/5310264/9598962/319da398-5090-11e5-8586-528ef2320828.jpg)

![vshithuberror5](https://cloud.githubusercontent.com/assets/5310264/9598976/4a41ae4e-5090-11e5-8d66-1269deea20b9.jpg)

![vsgithuberror6](https://cloud.githubusercontent.com/assets/5310264/9598977/4d6f27d6-5090-11e5-8ac2-b8df73496c37.jpg)

![vsgithuberror7](https://cloud.githubusercontent.com/assets/5310264/9598986/5035cc2c-5090-11e5-9799-998197ac47fe.jpg)

**Comment by Haacked** [comment]
Ah, ok. So you used the "Publish to Remote Repository" control. That's not part of the GitHub Extension (sorry this is so confusing).

What happens if you used the "Publish to GitHub" control instead? Probably something similar.

Also, keep in mind that "Publishing" means that you're going to create the repository on the server. But in this scenario, you already have a repository on the server. As far as Git is concerned, these are two different repos. If you create a repository on GitHub first with a gitignore, you should clone it locally rather than create a local one and then try to publish it.

I suppose we can make the error message a little better.

**Comment by shana** [comment]
After you went through the "Publish to Remote Repository" section to set up the remote, did the "Publish to GitHub" section get hidden?

**Comment by thecarlo** [comment]
Well, if you create a repo without the .gitignore on GitHub and then follow the exact same steps then everything works fine.

But if you created it with a .gitignore you get the error. Hope that makes sense.

**Comment by thecarlo** [comment]
>After you went through the "Publish to Remote Repository" section to set up the remote, did the "Publish to GitHub" section get hidden?

I can't remember - will have to reproduce it to see

**Comment by shana** [comment]
@thecarlo just to clarify: you went through "Publish to Remote Repository", and then you went through "Publish to GitHub", correct?

**Comment by thecarlo** [comment]
The last step was to click on Publish to Remote Repository and I pasted the https url of my git repo.
Then I got the error as per screengrab that appears below the publish button.

The Publish to GitHub section in the screengrab was not used at all, it was just pre-populated for some reason in VS.

**Comment by shana** [comment]
Ah, ok, I understand.

The "Publish to Remote Repository" is a section provided by MS. It's setting the remote and then pushing your changes. When you originally created the repository on GitHub and added the .gitignore file (or a README, it would do the same thing), GitHub created an initial commit for you, to add the file to the repo. So when "Publish to Remote Repository" tries to push your local commit, it fails because the local repository has no common commits with the remote one (both have only one commit).

In this scenario, you can clone the new repo that you created at GitHub via the Clone button in the Connect area. It will show up in the list of Local Repositories in the Connect page, and if you double click it, the repository will become active. Then you can create a new project (the default path for the Create New Project dialog will be set to where you cloned the repository to. make sure you double check that) and proceed as normal.
