### ISSUE TITLE
xUnit Tests not discovered

### ISSUE THREAD

**Issue by redowl3** [github/VisualStudio#691]
Hello! Please read the contributing guidelines before submitting an issue.

- Visual Studio version: 2017

__What happened__ (with steps, logs and screenshots, if possible)

Create new solution with ASP.NET Core project and update all nuget references (as of 18th November 2016).  Add xunit project, unit tests are not discovered.

**Comment by tocsoft** [comment]
@redowl3 this project is only "GitHub for Visual Studio" extension not the repo for VS itself.

You will want to report this issue directly to Microsoft by using the "Send Feedback" option in VS to let them know of the issue.

**Comment by redowl3** [comment]
Hello?! Not sure if you're are an adult responding to this thread but please read the contributing guidelines to not being a total idiot. If I've added a comment to the wrong thread then I apologise but these repos are clearly not well enough defined. Bloody clown.

**Comment by shana** [comment]
@redowl3 I can't believe I have to say this, I would assume it would be obvious, but offensive and insulting language will absolutely not be tolerated around here. There is no excuse for replying the way you did, and it is especially egregious given that @tocsoft was merely guiding you to the correct place where you should be reporting your issue. I'm deleting your comment as it is completely inappropriate and inexcusable.

As a reminder, because apparently this is something not completely obvious:

**Be respectful**: Not all of us will agree all the time, but disagreement is no excuse for poor behavior and poor manners. We might all experience some frustration now and then, but we cannot allow that frustration to turn into a personal attack. It’s important to remember that a community where people feel uncomfortable or threatened is not a productive one.

**Be careful in the words that we choose**: we are a community of professionals, and we conduct ourselves professionally. Be kind to others. Do not insult or put down other participants.
