### ISSUE TITLE
Missing submodule

### ISSUE THREAD

**Issue by masaeedu** [github/VisualStudio#70]
There seems to be a "scripts" submodule in the root pointing to revision [7ee5265...](https://github.com/github/VisualStudioBuildScripts/tree/7ee5265a5d86f02efa95a10bc2ebea50ab0f6d04) of a nonexistent https://github.com/github/VisualStudioBuildScripts/ repository. Going to that link 404s. This causes problems when cloning. 

Is this broken or am I misunderstanding how the submodule is supposed to work?

**Comment by masaeedu** [comment]
Nevermind, didn't realize those were for Github's CI.

**Comment by shana** [comment]
@masaeedu Did you get it working? I tried to make the build instructions as clear as possible regarding this bit, were they good enough or do they need improving?

**Comment by masaeedu** [comment]
@shana Yes, I managed to get it working, thanks. I ran into a few more hitches because of the default Configuration, but that's mostly my fault for not checking it (the Debug configuration has some class libraries set to build in Release mode, which causes IntelliSense to start complaining about everything from that class library being missing, even though the build succeeds). Overall, things went smoothly.

**Comment by shana** [comment]
@masaeedu Ah yes, the Release mode on some projects is on purpose (they would be nuget packages if I didn't need to sign them all). Didn't notice IntelliSense getting confused by it - but then again, it's been a while since I've done a build from scratch, which tends to give some different results when bootstrapping everything. Good to hear you got it working ^_^
