### ISSUE TITLE
Refresh button doesn't clear out the commit fields

### ISSUE THREAD

**Issue by amytruong** [github/VisualStudio#73]
Refresh button doesn't clear out the commit message field

**Steps to reproduce:**
1. Enter text in the "Enter in a Commit message (Required) field
2. Hit the Refresh button

**Expected Results:** I feel when I hit refresh (because I haven't saved the commit) that maybe the field should be cleared out? 

**Actual Results:** Nothing happens right now. Again, this was just something I was confused about so this may totally not be a bug but something I noticed.
![screen shot 2015-09-04 at 11 16 15 am](https://cloud.githubusercontent.com/assets/10725993/9691441/586b68b6-52f7-11e5-89a4-d0a246723d25.png)

These are other places where I think the Refresh button would clear these fields out?

![screen shot 2015-09-04 at 11 23 52 am](https://cloud.githubusercontent.com/assets/10725993/9691486/9313ecc2-52f7-11e5-9ff6-ce0ae8d24e9e.png)
![screen shot 2015-09-04 at 11 24 39 am](https://cloud.githubusercontent.com/assets/10725993/9691490/971a34de-52f7-11e5-9eb6-34b64d85ae9d.png)

**Comment by shana** [comment]
The commit area is a part of Team Explorer and not handled by us. The only part in these screenshots that is ours is the Publish to GitHub area.

Now in the case of the commit area clearing the fields when you hit refresh, it depends on whether the refresh button is intended to bring out new information that VS isn't aware of (say, a new file that's been added to the repository outside of VS), or whether the refresh button is intended to reset the state. In the first case, I wouldn't want it clearing the fields, because it's just refreshing the screen with new information that the user can't fill in (so not touching the user input fields makes sense). In the second case, if it's job is resetting the screen, then yes, makes sense to clear the fields. I can see a good reasoning for both, and I'm inclined to think that the refresh button is intended to update the information on screen without touching user input fields.

In the case of the Publish to GitHub form, the question is then: do we treat the refresh button as a reset button, or not? Also keeping in mind that the other user input fields on that page are not controlled by us (the Publish to Remote Repository and other Publish sections that might live there) and we can't make them follow our behavior.

I'm inclined to never touch user input fields unless it's very clear what a button does. If we reset the description field when the user clicks refresh, is that something that the user is expecting?

**Comment by shana** [comment]
I'm going with treating the button as a refresh button, not a reset button, so we won't clear the fields.
