### ISSUE TITLE
Publish to GitHub button in TE does not support high contrast

### ISSUE THREAD

**Issue by abuchholtzau** [github/VisualStudio#796]
Steps
1. Set Windows 10 to High Contrast mode
2. Open VS
3. Click publish button in the bottom right corner of VS
4. Look at the GitHub option 

![scr_rc5lf4d0 zuh](https://cloud.githubusercontent.com/assets/3174849/22271005/4cbd69fc-e247-11e6-911c-210d35761e6b.jpg)

**Comment by grokys** [comment]
Hi @abuchholtzau,

Yes this is currently failing because we're using a hack to detect the current VS theme and mistakenly identifying the high-contrast theme for a light theme.

The code to detect the current theme is here:

https://github.com/github/VisualStudio/blob/master/src/GitHub.VisualStudio.UI/Colors.cs#L35

There must be a better way to detect the current VS theme, but all I've found from googling are methods that involve reading a registry key, which strikes me as rather non-future-proof. How should we be detecting the current theme?

**Comment by abuchholtzau** [comment]
@prasethu can you help advise a better way to detect the VS theme?

**Comment by prasethu** [comment]
@abuchholtzau @grokys The right way to do this would be to apply the Platform button style in XAML directly on your button.

<UserControl
    xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
    xmlns:vsfx="clr-namespace: Microsoft.VisualStudio.Shell;assembly=Microsoft.VisualStudio.Shell.15.0">
    <Button
        Style="{DynamicResource {x:Static vsfx:VsResourceKeys.ButtonStyleKey}}" />
</UserControl>

**Comment by grokys** [comment]
Thanks @prasethu, it turns out we were overriding the default button style. Removing our overridden default button styled fixed it.

It would still be useful if there was a decent way to detect the current theme, but that's now a separate issue.

**Comment by prasethu** [comment]
@grokys  Why do you want to know what the current theme is? Your code should be agnostic to themes because we can add or change themes as we please.

**Comment by prasethu** [comment]
@grokys If this is specific to HighContrast, then there is the standard way:

'SystemParameters.HighContrast'
