### ISSUE TITLE
Include VSIX installer artifact in Appveyor build

### ISSUE THREAD

**Issue by jcansdale** [github/VisualStudio#799]
It would be useful for testing if the VSIX artifact was available when Appveyor builds a PR.

For example here:
https://ci.appveyor.com/project/github-windows/visualstudio/build/1290/artifacts

**Comment by grokys** [comment]
Out of interest, what is your use-case for artifacts from PRs?

**Comment by jcansdale** [comment]
Just an easy way to test a clean build when a new PR becomes available. Useful if something breaks to test a few different versions and hopefully find the PR that introduced the issue. 😄

**Comment by grokys** [comment]
True, I guess I'm just used to building from source and using `git bisect` to find problems!

**Comment by jcansdale** [comment]
You git ninja you. 😄

**Comment by StanleyGoldman** [comment]
🛑 👀 👂
[Git Bisect](https://git-scm.com/docs/git-bisect)

**Comment by shana** [comment]
To be able to do this properly, we'll need a few changes to the way the build works, and there's a few problems to solve on this front:

**Have unique versions for every build**

To make sure that build artifacts can be uniquely identified, every build needs to have its own unique version. Right now we only bump the version on a release and only that build produces artifacts (guaranteeing uniqueness). If we produce artifacts continuously, then versions need to be bumped continuously in some fashion.

AppVeyor has a build counter we could use for this, but the versions are in C# code, so C# code needs to be changed in order to produce the correct version build. If we commit this change, not only is that going to trigger another build, but all branches that get versions automatically bumped will conflict with each other and cause merge conflicts with master for other PRs. Appveyor does two different types of build - builds of the tip of a PR branch, and builds from the result of merging the PR source and target branch. If we hypothetically did a commit with a version bump in CI before having it build, we wouldn't be able to push this commit in the case of a PR merge build.

So, doing automatic version bumps in CI is annoying. We are also running two different CI environments, one internal and one external - which one does the bump and produces artifacts? who gets to push?

So how to sort this out? Perhaps only producing artifacts on an explicit version bump, meaning CI looks at the top commit and if it's a version bump, it produces artifacts? 

**Builds from external PRs aren't actually usable**

Builds from PRs coming from forks are "public" builds that don't include required information to access the API, so they're not usable at all and are only useful for running unit tests (which don't require real API access). That means that we can only produce artifacts for builds done in branches in the VisualStudio repository.

**Comment by jcansdale** [comment]
> To make sure that build artifacts can be uniquely identified, every build needs to have its own unique version.

Is it really necessary to uniquely version stamp all of the assemblies for an experimental build? What I've done on other projects is have some label showing that it's an experimental build and only version stamp the installer itself.

> AppVeyor has a build counter we could use for this, but the versions are in C# code, so C# code needs

Alternatively, we could update the `SolutionInfo.cs` file as part of scripted/CI builds (but not push it). At the moment we're using `2.2.0.5`. This could be changed to `2.2.5.777` (with trailing build number).

**Comment by shana** [comment]
> Is it really necessary to uniquely version stamp all of the assemblies for an experimental build?

Yeah, anyone can download things, so it would become a problem figuring out which code matches a certain version. Every code snapshot needs to match a unique identification, otherwise madness will ensue. It's annoying, but it guarantees we always know exactly what is running how and where - it's the only way to be sure. I guarantee you that if we publish automatically-built vsix packages, people will install them, no matter how many experimental labels we stuff on them :P

> Alternatively, we could update the SolutionInfo.cs file as part of scripted/CI builds (but not push it). At the moment we're using 2.2.0.5. This could be changed to 2.2.5.777 (with trailing build number).

That would break the match between the code that is built and the code snapshot that the code corresponds to. It's not a huge deal, but how would we tell that version 2.2.5.777 corresponds to a particular commit? We might need to save the commit hash in the assembly or vsix if we do this, so we can know where things came from.

**Comment by jcansdale** [comment]
> We might need to save the commit hash in the assembly or vsix if we do this, so we can know where things came from.

The last number could be the first 4 (hex) digits of the SHA. While not guaranteed to be unique, we'be still be unlikely to get a collision. It would then be trivial to clone the exact source, knowing just the version number. In the unlikely case of a collision, we could still use the version number for disambiguation. 😄

**Comment by jcansdale** [comment]
We could simply disable generation of the VSIX if it isn't being used to speed up the build. Assuming building it isn't still a useful sanity check?

We can continue discussion here:
https://github.com/github/VisualStudioBuildScripts/issues/6
