### ISSUE TITLE
Should return to PR list after creating a PR

### ISSUE THREAD

**Issue by grokys** [github/VisualStudio#805]
After creating a PR from the GitHub pane, the view should switch to the PR list. Instead it remains on the "Create Pull Request" view.

**Comment by paladique** [comment]
This seems most likely to happen when pushing a new branch when making a PR

**Comment by paladique** [comment]
Thought that ⬆️ was the reason, but it actually happens any time you switch branches.  I put some logging in place to try and find some common patterns while debugging. Noticed `Start()` in `UIController` is getting called twice. The call stack led to the `RepoChanged` method:
https://github.com/github/VisualStudio/blob/ca6aa0d52458d3339388b262578105963c3ce4e1/src/GitHub.VisualStudio/UI/Views/GitHubPaneViewModel.cs#L125-L126

That led to





Stays on PR Creation View
```
Start (54397957)
Firing Next from None (54397957)
Firing Next from None for flow PullRequestCreation (54397957)
Where::CredentialManager
   credential manager found at 'C:\Program Files\some\directory`
Start (55444801)
Firing Next from None (55444801)
Firing Next from None for flow PullRequestCreation (55444801)
VM: PR Creation Done at 1/31/2017 4:22:26 PM
VIEW: PR Creation Notified Done at 1/31/2017 4:22:26 PM
Firing Next from PRCreation (55444801)
Firing Next from PRCreation for flow PullRequestCreation (55444801)
Firing Next from End (55444801)
Firing Next from End for flow PullRequestCreation (55444801)
Disposing (55444801)
NAV: Controller Pop at 1/31/2017 4:22:26 PM
NAV: Controller reload at 1/31/2017 4:22:26 PM Busy?False
Firing Reload from PRCreation (54397957)
```

Goes to PR List View
```
Start (29498151)
Firing Next from None (29498151)
Firing Next from None for flow PullRequestCreation (29498151)
VM: PR Creation Done at 1/31/2017 4:20:36 PM
VIEW: PR Creation Notified Done at 1/31/2017 4:20:36 PM
Firing Next from PRCreation (29498151)
Firing Next from PRCreation for flow PullRequestCreation (29498151)
Firing Next from End (29498151)
Firing Next from End for flow PullRequestCreation (29498151)
Disposing (29498151)
NAV: Controller Pop at 1/31/2017 4:20:36 PM
NAV: Controller reload at 1/31/2017 4:20:36 PM Busy?False
Firing Reload from PRList (16458760)
```

**Comment by shana** [comment]
Ah, so it is because there's two PRCreation views getting pushed to the navigation history so that when it goes "back", it goes back to the previous creation view that was pushed. Legit bug! This is likely easy to reproduce by just clicking "Refresh" when in the creation view, and then hitting back - it's probably that it will just go back to the "previous" creation view instead of the PR list.

The `NavigationController` that's loading things into the history has a `Reload` method that refreshes views in place instead of loading a new one. When `GitHubPaneViewModel` asks for the PR list to be loaded, and it's already the current one, the `NavigationController` knows how to handle that and just reloads it in place (https://github.com/github/VisualStudio/blob/master/src/GitHub.App/Controllers/NavigationController.cs#L73).

The creation view always causes a new view to be pushed, however: https://github.com/github/VisualStudio/blob/master/src/GitHub.App/Controllers/NavigationController.cs#L69).

It's fine to create a new view in this case and just throw the current view data away, but if the new view is of the same type as the current view, then we should not be adding it twice to the history, we should be popping the existing one and pushing the new one.
