### ISSUE TITLE
Tweak the default and context menu behaviours of the PR details changes list

### ISSUE THREAD

**Issue by shana** [github/VisualStudio#817]
The list of files that have been changed in the PR details view currently have a context menu that contains "Open" and "Compare". This is a bit confusing depending on whether the PR branch is checked out or not, we should make these actions clearer, so here's a proposal:

- [ ] Default action (double click) is always to open a diff of the file
- [ ] Context menu entry "Preview" always opens a temporary copy of the file (our current "Open" behaviour)
- [ ] Context menu entry "Open" is only available if the PR branch is checked out, and it opens the actual real file that is on the local clone (regardless of whether a solution is opened or not)

Context menu would also contain #816 

Thoughts?

**Comment by jcansdale** [comment]
This is my no.1 usability issue at the moment. The fact that there's no way to open the actual real file and you can't even copy/paste the file name to find it is a pain!

I agree pretty much with your list (the current UI is definitely confusing). Here's your list with a few tweaks.

- [ ] Default action (double click) is always to open a diff of the file
- [ ] If the PR branch is checked out, the right hand file is live/editable (this is really handy).
- [ ] Having a "Preview" option can be misleading because live warnings/errors are missing (but the code still looks the same). The user can already preview the file via diff, so I'd be inclined to remove this option.
- [ ] Context menu entry "Open" is only available if the PR branch is checked out, and it opens the actual real file that is on the local clone (regardless of whether a solution is opened or not).

Does that make sense? 😄

**Comment by jcansdale** [comment]
I've prototyped the editable diff/file functionality in 2cd47ab4dfe4ff7509e0b91c323cb9a08ed67668. If the current branch is up to date, a live editable diff/file will be opened. I find the editable diff particularly useful.

Here's a pre-built version if you'd like to give it a try:
[GitHub.VisualStudio.zip](https://github.com/github/VisualStudio/files/777080/GitHub.VisualStudio.zip)

I find having something to play with can help refine ideas. 😄

**Comment by grokys** [comment]
Related: #801
