### ISSUE TITLE
Pull request list filters disabled for extended period of time

### ISSUE THREAD

**Issue by paladique** [github/VisualStudio#843]
In version 2.2.0.7, when switching to the pull request list in either direction (cancelling creation form, refreshing, pressing the PR toolbar icon, clicking TE Pull Request button) the filters at the top of the list stay disabled well after the list is loaded. They eventually are enabled, around 10 -15 seconds later. 

The problem in detail is this: 

> We save the current filter setting for loading the next time the list is shown, however, that setting can't be applied until the PR list is loaded because the filter choices aren't known until the list is loaded; we can only set the filter to something that's in the dropdown.
> 
> However the problem in #450 was that if the user changed the filter setting whilst the list was loading, then that choice would be overridden when the list finishes loading!
> 
> A better solution might be to allow the user to change the filters while loading, but if this happens, don't restore the state for that filter once load finishes.

I was able to take my time and open the snipping tool and get a screenshot before they were enabled, with a few more seconds to spare:

![capture](https://cloud.githubusercontent.com/assets/1414307/22749472/7471944a-edfb-11e6-888a-f92055af5414.PNG)

Looks like this when loaded:
![loaded](https://cloud.githubusercontent.com/assets/1414307/22749490/8fc84c52-edfb-11e6-8192-19529e62c0ad.PNG)

**Comment by grokys** [comment]
Yeah, disabling the filters while loading was a hacky way of fixing #450.

What we really need to is sort out the logic for loading the initial filter state, and a busy indicator at the top of the view!

**Comment by grokys** [comment]
To give more background to this issue:

We save the current filter setting for loading the next time the list is shown, however, that setting can't be applied until the PR list is loaded because the filter choices aren't known until the list is loaded; we can only set the filter to something that's in the dropdown.

However the problem in #450 was that if the user changed the filter setting _whilst_ the list was loading, then that choice would be overridden when the list finishes loading!

A better solution might be to allow the user to change the filters while loading, but if this happens, don't restore the state for that filter once load finishes.
