### ISSUE TITLE
Support for VS2013/VS2012

### ISSUE THREAD

**Issue by japj** [github/VisualStudio#9]
Unfortunately it is not yet possible to use VS2015 for everything (depending on the dependencies in a software project - i.e. currently it is only possible to do SQLServer 2012 SSIS development in VS2012, there might be other reasons aswell).

It would be good to also support VS2013/VS2012 with the Github VisualStudio plugin.

When developing this plugin, did you have a look at supporting multiple versions of VisualStudio and how difficult would it be to add support?

**Comment by Haacked** [comment]
The extension takes advantage of some new extensibility points added to Visual Studio 2015. But most of that is how we extend Team Explorer.

However, since we would not ship "in-the-box" with Visual Studio 2013, we could implement the dialogs and have them launch via a menu (instead of Team Explorer). So we'd miss out on the Team Explorer integration, but we'd have everything else.

At minimum, it'd be nice to start with the authentication piece since it handles the two-factor authentication for people and is very useful. That would make a very nice community contribution. :smile:

**Comment by shana** [comment]
What @Haacked said :smile:

Besides the Team Explorer UI that we're integrated into in VS 2015 (which exists in 2013 but not sure whether the APIs are the same), we're using a VS api for cloning a repo, which definitely doesn't exist in VS 2013. There might be another service or two that we use that I'm not sure whether they're 2015 only.

**Comment by RandomlyKnighted** [comment]
In the [SideWaffle](https://github.com/ligershark/side-waffle/blob/autoupdate/TemplatePack/Tooling/DynamicTemplateBuilder.cs#L106) extension, we are using the Repository class to clone a repo. If I remember correctly, this was a VS API class. We've tested it on VS 2013. I'm not certain if we've tested it on VS 2012.

**Comment by omoefizy** [comment]
![vs](https://cloud.githubusercontent.com/assets/18389835/19246334/6bd5001c-8f58-11e6-9222-08c54f3409b2.PNG) you can view this VS Community picture. Click on tools manage connection

**Comment by shana** [comment]
I don't think we really want to do this anymore.
