### ISSUE TITLE
'Must authenticate to access this API' when trying to log in. 

### ISSUE THREAD

**Issue by waldnzwrld** [github/VisualStudio#924]
Hello! Please read the contributing guidelines before submitting an issue regarding the GitHub Extension for Visual Studio.

- GitHub Extension for Visual Studio  version:
- Visual Studio version:

__What happened__ (with steps, logs and screenshots, if possible)

At some point (i'm not sure when) I was logged out of GitHub in Visual Studio, every time I try and Log In I just get a red exclamation with no further information.
![visualstudioconnectionerror](https://cloud.githubusercontent.com/assets/4338862/23910097/de7f8e64-0895-11e7-9cc7-15909b30d3e8.png)

In the `extension.log`  the error message is:

```
Got an authorization exception
Octokit.AuthorizationException: Must authenticate to access this API.
...
...
Error logging into 'http://[hostname]/' as '[username]'
System.InvalidOperationException: git:http://[hostname]
```

**Comment by i-make-razors** [comment]
Hello,

This issue was occuring on two of our workstations when attempting to connect to our GitHub Enterprise server. Both workstations were running:
Visual Studio 2015: 14.0.25424.00 Update 3
GitHub for Visual Studio Extension: 2.2.0.8
All running on Windows 7

Every time we attempted to connect using the extension we simply got a red exclamation icon without any other indicators as to what the problem was. I think at a minimum this needs to be addressed to provide better feedback as to what the error is.

In the extension.log file we started seeing the OctoKit authorization exception message on one workstation and on another workstation we started seeing an InvalidOperationException without any further details.

Using CURL we were able to verify the server was accepting connections, and that the issue was on the workstations and not the server. What was very interesting to me was that when I sent a CURL request to the server using an invalid password I received a "bad credentials" message from the server. This was contrasted with the error in the extension.log file which was "you must authenticate" which seemed to indicate to me that the extension wasn't even passing credentials to the server API.

After some back & forth, I ended up deleting all of our servers entries in the Windows Credential Manager and was finally able to reconnect. On the other workstation we attempted to perform the same fix (remove the credentials) but were still unable to connect to the server. Eventually we discovered that the VS instance **had to be running as an administrator** to allow the extension to connect. This wasn't immediately apparent on the previous workstation since it was running with a lower UAC setting.

**Comment by shana** [comment]
Apologies for the lack of response on this issue 😞 

Is this still happening for you?

**Comment by i-make-razors** [comment]
Yes, this is still a problem. The extension works, but when I try and push any changes to our GHE server I get an error that I must be authenticated, but I can not log in without restarting VS and running as an Administrator.

________________________________

**Comment by grokys** [comment]
@i-make-razors an update - I'm _hoping_ this will be resolved in our next minor release which should be out early next year.

**Comment by grokys** [comment]
@i-make-razors is this still an issue?

**Comment by imakerazors** [comment]
@grokys We gave up using the extension and switched to GitKraken about 10 months ago.
