### ISSUE TITLE
Logging out does not prevent pushing

### ISSUE THREAD

**Issue by khatharr** [github/VisualStudio#929]
If I publish a repo to github and then log out of github from the plugin I am able to continue pushing, even after restarting VS.

This concerns me because it means that logging out does not protect my remote repo from unauthorized changes.

**Comment by paladique** [comment]
Hi @khatharr,

Pushing to a remote repo is part of the Git functionality provided by Visual Studio. Because you have a local repository with a remote repo, Git allows you to push to your remote, regardless of whether you have the extension installed or not, regardless of where your remote repository is hosted. This is because those push operations are Git specific. I hope that clears that up!

You can find more information on the features that our extension provides [here](https://marketplace.visualstudio.com/items?itemName=GitHub.GitHubExtensionforVisualStudio).
