### ISSUE TITLE
Check .snk file in to public repository.

### ISSUE THREAD

**Issue by grokys** [github/VisualStudio#965]
Currently our .snk files are in a private submodule, which keeps causing problems for us and also makes it harder for OSS contributors. Immo Landwerth (.NET program manager) has this to say:

> Dear OSS maintainers: unless your keys are in hardware or used for sandboxing, just check in your .snk files. It's much easier.
> https://twitter.com/terrajobst/status/848560465672151040

Thoughts?

**Comment by shana** [comment]
The .snk file is in a private submodule to guarantee that the runtime loads our builds and not any random build that someone else might be playing with. If we put the snk file in the public repo, anyone trying out their own clone of the extension will cause our extension to fail, it's not like people are going to remember to bump the version to avoid breaking the installed version of the extension while they're playing around with the code.

The signature is a part of the version that the runtime identifies when determining what to load. The public code can have an snk file used just for public builds while we sign with a different, private key. The key used for official releases should never be out in the open.

**Comment by grokys** [comment]
I don't understand though - internally, we have the private .snk file, and I can quite happily run dev builds in the experimental instance without interfering with the version installed on the main instance. To interfere with the version installed on the main VS instance I need to explicitly install it there. If one doesn't bump the version then the install will fail.

**Comment by shana** [comment]
If you have DLLs loaded before our extension loads and they have the same version and signing key, our extension will use those DLLs instead of ours. This is how the Xamarin plugin was able to break us on launch. We don't just sign our own things, we sign dependencies like octokit and akavache as well to ensure that when we ask for a library, we get exactly what we expect. The signing key is private literally because our extension got broken due to dependencies with the same version and signing key but different code being loaded before we do, so it's not just a theoretical exercise 😄 

Putting our internal signing key into the public is not actually what that tweet is all about, however. What OSS maintainers and scenarios is that tweet referring to? .NET libraries are useless without signing (also why we sign our dependencies). If you want to fix a bug on a library you depend on, you must have the original key in order to replace the library with your version and be able to use it without recompiling your application. That's a really important reason why the key should be public.

The extension, however, is not a library. People should not be creating builds of their own that indistinguishable from our official builds, because the extension is one whole package, it's not a component for reuse. Therefore, the signing key we use to version the extension should not be public, so we are sure that we know exactly what code is running when it's installed. We can certainly put an alternate public signing key in the repo that non-official builds can use, because signing is still a part of versioning and that way people don't have to do that manual part on their own (which they can).

**Comment by grokys** [comment]
Ok, will close this issue, thought this might be useful for future reference anyway ;)

**Comment by shana** [comment]
Yeah I don't think we ever wrote this down so definitely useful!
