### ISSUE TITLE
Enhancement: Allow fork+clone

### ISSUE THREAD

**Issue by weitzhandler** [github/VisualStudio#985]
- GitHub Extension for Visual Studio  version: 2.2.0.11
- Visual Studio version: 15.1 (26403.7)

Cloning repositories is only possible for repositories in my organizations.
Please add an option to clone (by forking) ANY GitHub repo. Also when clicking "Open in Visual Studio" in the website, this what should happen.

**Comment by grokys** [comment]
Yep, I agree this would be nice!

Related: #792.

**Comment by jcansdale** [comment]
@weitzhandler you will be able to fork a repo that you've already cloned in the upcoming release (by end of this week).  i've found this to be more useful than a combined clone+fork, because you don't necessarily know if your idea will work ahead of time (e.g. if you're hoping to submit a PR).

> Cloning repositories is only possible for repositories in my organizations.

This is a priority for the next release.
